import type { Book } from "@/components/BookReader";
import { lessonPage, gardenPage, speakPage, unitPage, poemPage, strokePage } from "./grade1";

// 四年级 · 上册（部编版四年级上册结构）
export const grade4Book: Book = {
  gradeId: "g4",
  title: { en: "Grade 4 · Book One", zh: "四年级 · 上册" },
  subtitle: { en: "Nature, Myths & Heroes", zh: "自然、神话与英雄" },
  pages: [
    { kind: "cover", title: { en: "Cover", zh: "封面" } },
    { kind: "copyright", title: { en: "About", zh: "出版说明" }, body: { en: <>Grade 4 Book One, after the PEP fourth-grade textbook.</>, zh: <>《四年级 · 上册》，按部编版四年级上册结构编写。</> } },
    { kind: "toc", title: { en: "Contents", zh: "目录" } },

    unitPage("一", "自然之美", "Natural Beauty", "观潮、走月亮、繁星。", ["观潮", "走月亮", "繁星"]),
    ...lessonPage({
      zhTitle: "观潮", enTitle: "Watching the Tide", pinyin: "guān cháo",
      passage: [["qián","钱"],["táng","塘"],["jiāng","江"],["dà","大"],["cháo","潮"],["，","，"],["zì","自"],["gǔ","古"],["yǐ","以"],["lái","来"],["bèi","被"],["chēng","称"],["wéi","为"],["tiān","天"],["xià","下"],["qí","奇"],["guān","观"],["。","。"]],
      note: "钱塘江大潮是天下奇观。潮来前、潮来时、潮头过后，声音和样子变化壮观。",
      recognize: [{ch:"潮",py:"cháo",word:"大潮"},{ch:"罩",py:"zhào",word:"笼罩"},{ch:"蒙",py:"méng",word:"蒙蒙"},{ch:"沸",py:"fèi",word:"沸腾"}],
      write: [{ch:"潮",py:"cháo",strokes:15,radical:"氵",word:"大潮"},{ch:"称",py:"chēng",strokes:10,radical:"禾",word:"称为"},{ch:"盐",py:"yán",strokes:10,radical:"皿",word:"盐官"},{ch:"罩",py:"zhào",strokes:13,radical:"罒",word:"笼罩"}],
      practice: ["朗读课文，背诵第3、4自然段。","潮来前、潮来时、潮头过后各是什么样？","为什么说大潮是天下奇观？"],
      think: "你见过什么壮观的景象？",
    }),
    ...lessonPage({
      zhTitle: "走月亮", enTitle: "Walking under the Moon", pinyin: "zǒu yuè liang",
      passage: [["qiū","秋"],["tiān","天"],["de","的"],["yuè","月"],["liang","亮"],["shēng","升"],["qǐ","起"],["lái","来"],["le","了"],["。","。"]],
      note: "我和阿妈在月光下走，走过溪边、田埂。月光下的景色美，亲情暖。",
      recognize: [{ch:"鹅",py:"é",word:"鹅卵石"},{ch:"卵",py:"luǎn",word:"鹅卵石"},{ch:"俗",py:"sú",word:"风俗"},{ch:"跃",py:"yuè",word:"跃出"}],
      write: [{ch:"淘",py:"táo",strokes:11,radical:"氵",word:"淘洗"},{ch:"牵",py:"qiān",strokes:9,radical:"牛",word:"牵手"},{ch:"鹅",py:"é",strokes:12,radical:"鸟",word:"白鹅"},{ch:"卵",py:"luǎn",strokes:7,radical:"卩",word:"鹅卵石"}],
      practice: ["朗读课文。","我和阿妈走过哪些地方？","月光下景色怎样？"],
      think: "你和家人月下散过步吗？",
    }),
    ...lessonPage({
      zhTitle: "繁星", enTitle: "Stars", pinyin: "fán xīng",
      passage: [["wǒ","我"],["ài","爱"],["yuè","月"],["yè","夜"],["，","，"],["dàn","但"],["wǒ","我"],["yě","yě" as any].slice(0,2) as [string,string],["ài","爱"],["xīng","星"],["tiān","天"],["。","。"]],
      note: "巴金。从前、三年前、如今，三次看繁星，感受不同。星天让人回到童年。",
      recognize: [{ch:"繁",py:"fán",word:"繁星"},{ch:"昧",py:"mèi",word:"半明半昧"},{ch:"坠",py:"zhuì",word:"坠落"}],
      write: [{ch:"繁",py:"fán",strokes:17,radical:"糸",word:"繁星"},{ch:"漫",py:"màn",strokes:14,radical:"氵",word:"漫灭"},{ch:"灭",py:"miè",strokes:5,radical:"火",word:"消灭"},{ch:"藤",py:"téng",strokes:18,radical:"艹",word:"藤萝"}],
      practice: ["朗读课文。","作者三次看星各是什么感受？","为什么星天让人回到童年？"],
      think: "你看过满天星星吗？",
    }),
    gardenPage("一", ["识字加油站：自然字--潮、雾、霜、霞。","字词句运用：用比喻写潮水。","书写提示：左右结构的字注意穿插。","日积月累：鹿柴--空山不见人，但闻人语响。"], { zhTitle: "鹿柴", lines: ["空山不见人，", "但闻人语响。", "返景入深林，", "复照青苔上。"] }),

    unitPage("二", "提问与发现", "Questioning", "一个豆荚里的五粒豆、蝙蝠和雷达、呼风唤雨的世纪。", ["一个豆荚里的五粒豆", "蝙蝠和雷达", "呼风唤雨的世纪"]),
    ...lessonPage({
      zhTitle: "一个豆荚里的五粒豆", enTitle: "Five Peas in a Pod", pinyin: "yí gè dòu jiá lǐ de wǔ lì dòu",
      passage: [["yǒu","有"],["yí","一"],["gè","个"],["dòu","豆"],["jiá","荚"],["，","，"],["lǐ","里"],["miàn","面"],["yǒu","有"],["wǔ","五"],["lì","粒"],["dòu","豆"],["。","。"]],
      note: "安徒生。五粒豆各有志向，最后一粒落在窗台发芽开花，给生病的小女孩带来希望。平凡的豆做了最有意义的事。",
      recognize: [{ch:"荚",py:"jiá",word:"豆荚"},{ch:"豌",py:"wān",word:"豌豆"},{ch:"僵",py:"jiāng",word:"僵硬"},{ch:"苔",py:"tái",word:"青苔"}],
      write: [{ch:"豌",py:"wān",strokes:15,radical:"豆",word:"豌豆"},{ch:"按",py:"àn",strokes:9,radical:"扌",word:"按照"},{ch:"舒",py:"shū",strokes:12,radical:"舌",word:"舒服"},{ch:"恐",py:"kǒng",strokes:10,radical:"心",word:"恐怕"}],
      practice: ["朗读课文。","五粒豆各有什么志向？","最后一粒豆做了什么？"],
      think: "哪粒豆最有意义？为什么？",
    }),
    ...lessonPage({
      zhTitle: "蝙蝠和雷达", enTitle: "The Bat and the Radar", pinyin: "biān fú hé léi dá",
      passage: [["qīng","清"],["lǎng","朗"],["de","的"],["yè","夜"],["kōng","空"],["，","，"],["yì","一"],["zhī","只"],["biān","蝙"],["fú","fú" as any].slice(0,2) as [string,string],["cóng","从"],["tóu","头"],["shàng","上"],["fēi","飞"],["guò","过"],["。","。"]],
      note: "科学家通过三次试验发现蝙蝠靠嘴和耳朵（超声波）探路，据此发明雷达。仿生学。",
      recognize: [{ch:"蝙",py:"biān",word:"蝙蝠"},{ch:"蝠",py:"fú",word:"蝙蝠"},{ch:"雷",py:"léi",word:"雷达"},{ch:"达",py:"dá",word:"雷达"}],
      write: [{ch:"蝙",py:"biān",strokes:15,radical:"虫",word:"蝙蝠"},{ch:"蝠",py:"fú",strokes:15,radical:"虫",word:"蝙蝠"},{ch:"蚊",py:"wén",strokes:10,radical:"虫",word:"蚊子"},{ch:"即",py:"jí",strokes:7,radical:"卩",word:"即使"}],
      practice: ["朗读课文。","科学家做了几次试验？结果是什么？","雷达和蝙蝠探路有什么相同？"],
      think: "你还知道哪些仿生发明？",
    }),
    ...lessonPage({
      zhTitle: "呼风唤雨的世纪", enTitle: "The Century of Wind and Rain", pinyin: "hū fēng huàn yǔ de shì jì",
      passage: [["èr","二"],["shí","十"],["shì","世"],["jì","jì" as any].slice(0,2) as [string,string],["shì","是"],["yí","一"],["gè","个"],["hū","呼"],["fēng","风"],["huàn","唤"],["yǔ","雨"],["de","的"],["shì","世"],["jì","纪"],["。","。"]],
      note: "20世纪科技飞速发展，人类靠现代科技呼风唤雨。科技改变生活。",
      recognize: [{ch:"唤",py:"huàn",word:"呼唤"},{ch:"纪",py:"jì",word:"世纪"},{ch:"技",py:"jì",word:"科技"},{ch:"索",py:"suǒ",word:"探索"}],
      write: [{ch:"唤",py:"huàn",strokes:10,radical:"口",word:"呼唤"},{ch:"纪",py:"jì",strokes:6,radical:"纟",word:"世纪"},{ch:"改",py:"gǎi",strokes:7,radical:"攵",word:"改变"},{ch:"程",py:"chéng",strokes:12,radical:"禾",word:"程度"}],
      practice: ["朗读课文。","20世纪有哪些发明？","为什么说呼风唤雨？"],
      think: "科技给你生活带来什么变化？",
    }),
    speakPage("我们与环境", "讨论我们身边环境问题，提出保护建议。", ["说清楚问题和建议。", "听别人说，补充。"], ["河水脏了，我们要不乱扔垃圾。","空气不好，要多植树。"]),
    gardenPage("二", ["识字加油站：科技字--技、科、网、电。","字词句运用：用「没有……就没有……」说科技。","书写提示：注意「蝙」「蝠」的虫字旁。","日积月累：好问则裕，自用则小。"], { zhTitle: "题西林壁", lines: ["横看成岭侧成峰，", "远近高低各不同。", "不识庐山真面目，", "只缘身在此山中。"] }),

    unitPage("三", "神话故事", "Myths", "盘古开天地、精卫填海、普罗米修斯、女娲补天。", ["盘古开天地", "精卫填海", "普罗米修斯", "女娲补天"]),
    ...lessonPage({
      zhTitle: "盘古开天地", enTitle: "Pangu Opens the Sky", pinyin: "pán gǔ kāi tiān dì",
      passage: [["hěn","很"],["jiǔ","久"],["hěn","很"],["jiǔ","久"],["yǐ","以"],["qián","前"],["，","，"],["tiān","天"],["dì","地"],["hùn","混"],["dùn","沌"],["yì","一"],["piàn","piàn" as any].slice(0,2) as [string,string],["。","。"]],
      note: "盘古用斧头劈开混沌，顶天立地，死后身体化为万物。创世神话，想象伟大。",
      recognize: [{ch:"沌",py:"dùn",word:"混沌"},{ch:"斧",py:"fǔ",word:"斧头"},{ch:"劈",py:"pī",word:"劈开"},{ch:"撑",py:"chēng",word:"撑住"}],
      write: [{ch:"翻",py:"fān",strokes:18,radical:"羽",word:"翻身"},{ch:"劈",py:"pī",strokes:15,radical:"刀",word:"劈开"},{ch:"撑",py:"chēng",strokes:15,radical:"扌",word:"撑住"},{ch:"竭",py:"jié",strokes:14,radical:"立",word:"竭力"}],
      practice: ["朗读课文。","盘古怎么开天地？","盘古死后身体变成了什么？"],
      think: "盘古是个怎样的人？",
    }),
    ...lessonPage({
      zhTitle: "精卫填海", enTitle: "Jingwei Fills the Sea", pinyin: "jīng wèi tián hǎi",
      passage: [["yán","炎"],["dì","dì" as any].slice(0,2) as [string,string],["zhī","之"],["shào","少"],["nǚ","女"],["，","，"],["míng","名"],["yuē","yuē" as any].slice(0,2) as [string,string],["nǚ","女"],["wá","娃"],["。","。"]],
      note: "文言文。炎帝小女儿淹死化为精卫，衔木石填海。坚韧不拔。",
      recognize: [{ch:"炎",py:"yán",word:"炎帝"},{ch:"溺",py:"nì",word:"溺水"},{ch:"衔",py:"xián",word:"衔着"}],
      write: [{ch:"帝",py:"dì",strokes:9,radical:"巾",word:"皇帝"},{ch:"溺",py:"nì",strokes:13,radical:"氵",word:"溺水"},{ch:"衔",py:"xián",strokes:11,radical:"彳",word:"衔接"},{ch:"返",py:"fǎn",strokes:7,radical:"辶",word:"返回"}],
      practice: ["朗读并背诵文言文。","精卫为什么填海？","精卫精神是什么？"],
      think: "你佩服精卫吗？",
    }),
    ...lessonPage({
      zhTitle: "普罗米修斯", enTitle: "Prometheus", pinyin: "pǔ luó mǐ xiū sī",
      passage: [["hěn","很"],["jiǔ","jiǔ" as any].slice(0,2) as [string,string],["hěn","很"],["jiǔ","久"],["yǐ","以"],["qián","前"],["，","，"],["dì","地"],["shàng","上"],["méi","没"],["yǒu","有"],["huǒ","火"],["。","。"]],
      note: "希腊神话。普罗米修斯为人类盗火，被宙斯惩罚，不屈服。勇敢、为民。",
      recognize: [{ch:"普",py:"pǔ",word:"普罗米修斯"},{ch:"罗",py:"luó",word:"普罗"},{ch:"宙",py:"zhòu",word:"宙斯"},{ch:"斯",py:"sī",word:"斯"}],
      write: [{ch:"普",py:"pǔ",strokes:12,radical:"日",word:"普通"},{ch:"罗",py:"luó",strokes:8,radical:"罒",word:"罗列"},{ch:"悲",py:"bēi",strokes:12,radical:"心",word:"悲惨"},{ch:"惨",py:"cǎn",strokes:11,radical:"忄",word:"悲惨"}],
      practice: ["朗读课文。","普罗米修斯为人类做了什么？","他受到什么惩罚？"],
      think: "普罗米修斯为什么不屈服？",
    }),
    gardenPage("三", ["识字加油站：神话人物--盘古、精卫、普罗米修斯、女娲。","字词句运用：用「先……然后……」讲神话。","书写提示：注意「劈」「撑」的结构。","日积月累：嫦娥--云母屏风烛影深，长河渐落晓星沉。"], { zhTitle: "嫦娥", lines: ["云母屏风烛影深，", "长河渐落晓星沉。", "嫦娥应悔偷灵药，", "碧海青天夜夜心。"] }),

    unitPage("四", "观察与发现", "Observation", "爬山虎的脚、蟋蟀的住宅。", ["爬山虎的脚", "蟋蟀的住宅"]),
    ...lessonPage({
      zhTitle: "爬山虎的脚", enTitle: "The Feet of the Climbing Tiger", pinyin: "pá shān hǔ de jiǎo",
      passage: [["xué","学"],["xiào","校"],["lǐ","里"],["qiáng","墙"],["jiǎo","脚"],["shàng","shàng" as any].slice(0,2) as [string,string],["pá","爬"],["shān","山"],["hǔ","hǔ" as any].slice(0,2) as [string,string],["。","。"]],
      note: "叶圣陶。细致观察爬山虎的叶子和脚的形状、怎么爬。连续观察才能写清楚。",
      recognize: [{ch:"虎",py:"hǔ",word:"爬山虎"},{ch:"占",py:"zhàn",word:"占了"},{ch:"铺",py:"pū",word:"铺开"},{ch:"匀",py:"yún",word:"均匀"}],
      write: [{ch:"虎",py:"hǔ",strokes:8,radical:"虍",word:"老虎"},{ch:"占",py:"zhàn",strokes:5,radical:"口",word:"占领"},{ch:"铺",py:"pū",strokes:12,radical:"钅",word:"铺开"},{ch:"匀",py:"yún",strokes:4,radical:"勹",word:"均匀"}],
      practice: ["朗读课文。","爬山虎的脚长什么样？","它怎么往上爬？"],
      think: "作者为什么观察得这么细？",
    }),
    ...lessonPage({
      zhTitle: "蟋蟀的住宅", enTitle: "The Cricket's Home", pinyin: "xī shuài de zhù zhái",
      passage: [["xī","蟋"],["shuài","蟀"],["de","的"],["zhù","zhù" as any].slice(0,2) as [string,string],["zhái","宅"],["shì","是"],["wěi","wěi" as any].slice(0,2) as [string,string],["dà","大"],["de","的"],["gōng","工"],["chéng","程"],["。","。"]],
      note: "法布尔。蟋蟀的住宅是伟大的工程，它不肯随遇而安，自己一点一点挖。",
      recognize: [{ch:"宅",py:"zhái",word:"住宅"},{ch:"慎",py:"shèn",word:"慎重"},{ch:"择",py:"zé",word:"选择"},{ch:"址",py:"zhǐ",word:"地址"}],
      write: [{ch:"宅",py:"zhái",strokes:6,radical:"宀",word:"住宅"},{ch:"临",py:"lín",strokes:9,radical:"丨",word:"临时"},{ch:"慎",py:"shèn",strokes:13,radical:"忄",word:"慎重"},{ch:"址",py:"zhǐ",strokes:7,radical:"土",word:"地址"}],
      practice: ["朗读课文。","蟋蟀住宅有什么特点？","为什么说它是伟大的工程？"],
      think: "蟋蟀为什么不肯随遇而安？",
    }),
    gardenPage("四", ["识字加油站：观察字--占、铺、匀、叠。","字词句运用：用连续观察写一种植物。","书写提示：注意「虎」「铺」的结构。","日积月累：雪梅--梅须逊雪三分白，雪却输梅一段香。"], { zhTitle: "雪梅", lines: ["梅雪争春未肯降，", "骚人阁笔费评章。", "梅须逊雪三分白，", "雪却输梅一段香。"] }),

    unitPage("五", "历史人物故事", "Historical Figures", "王戎不取道旁李、西门豹治邺、为中华之崛起而读书。", ["王戎不取道旁李", "西门豹治邺", "为中华之崛起而读书"]),
    ...lessonPage({
      zhTitle: "王戎不取道旁李", enTitle: "Wang Rong and the Plums", pinyin: "wáng róng bù qǔ dào páng lǐ",
      passage: [["wáng","王"],["róng","róng" as any].slice(0,2) as [string,string],["qī","qī" as any].slice(0,2) as [string,string],["suì","suì" as any].slice(0,2) as [string,string],["，","，"],["cháng","cháng" as any].slice(0,2) as [string,string],["yǔ","yǔ" as any].slice(0,2) as [string,string],["zhū","zhū" as any].slice(0,2) as [string,string],["xiǎo","xiǎo" as any].slice(0,2) as [string,string],["er","儿"].slice(0,2) as [string,string],["yóu","游"],["。","。"]],
      note: "文言文。王戎七岁，见道旁李多而不动，说李必苦。善于观察推理。",
      recognize: [{ch:"戎",py:"róng",word:"王戎"},{ch:"尝",py:"cháng",word:"曾经"},{ch:"诸",py:"zhū",word:"诸位"},{ch:"竞",py:"jìng",word:"竞走"}],
      write: [{ch:"戎",py:"róng",strokes:6,radical:"戈",word:"戎装"},{ch:"尝",py:"cháng",strokes:9,radical:"小",word:"品尝"},{ch:"诸",py:"zhū",strokes:10,radical:"讠",word:"诸位"},{ch:"竞",py:"jìng",strokes:10,radical:"立",word:"竞争"}],
      practice: ["朗读并背诵文言文。","王戎为什么不取李？","王戎是个怎样的孩子？"],
      think: "你怎么知道李是苦的？（推理）",
    }),
    ...lessonPage({
      zhTitle: "为中华之崛起而读书", enTitle: "Reading for China's Rise", pinyin: "wèi zhōng huá zhī jué qǐ ér dú shū",
      passage: [["zhōu","周"],["ēn","ēn" as any].slice(0,2) as [string,string],["lái"," lái"].slice(0,2) as [string,string],["shí","shí" as any].slice(0,2) as [string,string],["èr","èr" as any].slice(0,2) as [string,string],["shí","shi" as any].slice(0,2) as [string,string],["suì","suì" as any].slice(0,2) as [string,string],["jiù","就"],["lái","lái" as any].slice(0,2) as [string,string],["dào","dào" as any].slice(0,2) as [string,string],["fèng","fèng" as any].slice(0,2) as [string,string],["tiān","tiān" as any].slice(0,2) as [string,string],["dú","dú" as any].slice(0,2) as [string,string],["shū","shū" as any].slice(0,2) as [string,string],["。","。"]],
      note: "周恩来少年时目睹中国人受欺，立志「为中华之崛起而读书」。志向远大、爱国。",
      recognize: [{ch:"崛",py:"jué",word:"崛起"},{ch:"范",py:"fàn",word:"模范"},{ch:"魏",py:"wèi",word:"魏校长"}],
      write: [{ch:"肃",py:"sù",strokes:8,radical:"肀",word:"严肃"},{ch:"晰",py:"xī",strokes:12,radical:"日",word:"清晰"},{ch:"振",py:"zhèn",strokes:10,radical:"扌",word:"振奋"},{ch:"胸",py:"xiōng",strokes:10,radical:"月",word:"胸怀"}],
      practice: ["朗读课文。","周恩来看到什么？","他立下什么志向？"],
      think: "你为什么读书？",
    }),
    gardenPage("五", ["识字加油站：志向字--志、崛、振、胸。","字词句运用：用「因为……所以……」说周恩来立志。","书写提示：注意「肃」「振」的笔顺。","日积月累：夏日绝句--生当作人杰，死亦为鬼雄。"], { zhTitle: "夏日绝句", lines: ["生当作人杰，", "死亦为鬼雄。", "至今思项羽，", "不肯过江东。"] }),

    unitPage("六", "童年趣事", "Childhood", "牛和鹅、一只窝囊的大老虎、陀螺。", ["牛和鹅", "一只窝囊的大老虎", "陀螺"]),
    ...lessonPage({
      zhTitle: "牛和鹅", enTitle: "The Ox and the Goose", pinyin: "niú hé é",
      passage: [["dà","大"],["jiā","jiā" as any].slice(0,2) as [string,string],["dōu","dōu" as any].slice(0,2) as [string,string],["shuō","shuō" as any].slice(0,2) as [string,string],["：","："],["niú","niú" as any].slice(0,2) as [string,string],["de","de" as any].slice(0,2) as [string,string],["yǎn","yǎn" as any].slice(0,2) as [string,string],["jing","睛"].slice(0,2) as [string,string],["kàn","kàn" as any].slice(0,2) as [string,string],["rén","rén" as any].slice(0,2) as [string,string],["xiǎo","xiǎo" as any].slice(0,2) as [string,string],["。","。"]],
      note: "大家说牛眼看人大、鹅眼看人小，所以我们怕鹅。后来换角度看，就不怕了。角度改变看法。",
      recognize: [{ch:"谓",py:"wèi",word:"所谓"},{ch:"拳",py:"quán",word:"拳头"},{ch:"膊",py:"bó",word:"胳膊"}],
      write: [{ch:"摸",py:"mō",strokes:13,radical:"扌",word:"摸头"},{ch:"甚",py:"shèn",strokes:9,radical:"甘",word:"甚至"},{ch:"跪",py:"guì",strokes:13,radical:"足",word:"跪下"},{ch:"捶",py:"chuí",strokes:11,radical:"扌",word:"捶背"}],
      practice: ["朗读课文。","我们为什么怕鹅？","后来为什么不怕了？"],
      think: "换个角度看问题有什么好？",
    }),
    gardenPage("六", ["识字加油站：动作字--摸、跪、捶、绕。","字词句运用：用动作写一件事。","书写提示：注意「跪」「捶」的足/扌旁。","日积月累：尺有所短，寸有所长。"], { zhTitle: "凉州词", lines: ["葡萄美酒夜光杯，", "欲饮琵琶马上催。", "醉卧沙场君莫笑，", "古来征战几人回？"] }),

    unitPage("七", "家国情怀", "Patriotism", "古诗三首、梅兰芳蓄须。", ["古诗三首", "梅兰芳蓄须"]),
    ...lessonPage({
      zhTitle: "梅兰芳蓄须", enTitle: "Mei Lanfang Grows a Beard", pinyin: "méi lán fāng xù xū",
      passage: [["méi","méi" as any].slice(0,2) as [string,string],["lán","lán" as any].slice(0,2) as [string,string],["fāng","fāng" as any].slice(0,2) as [string,string],["shì","shì" as any].slice(0,2) as [string,string],["jié","jié" as any].slice(0,2) as [string,string],["chū","chū" as any].slice(0,2) as [string,string],["míng","míng" as any].slice(0,2) as [string,string],["de","de" as any].slice(0,2) as [string,string],["jīng","jīng" as any].slice(0,2) as [string,string],["jù","jù" as any].slice(0,2) as [string,string],["yǎn","yǎn" as any].slice(0,2) as [string,string],["yuán","yuán" as any].slice(0,2) as [string,string],["yì","yì" as any].slice(0,2) as [string,string],["shù","shù" as any].slice(0,2) as [string,string],["jiā","jiā" as any].slice(0,2) as [string,string],["。","。"]],
      note: "梅兰芳在抗战时蓄须明志，宁可挨饿也不为日本人演出。民族气节。",
      recognize: [{ch:"蓄",py:"xù",word:"蓄须"},{ch:"扰",py:"rǎo",word:"打扰"},{ch:"拒",py:"jù",word:"拒绝"}],
      write: [{ch:"蓄",py:"xù",strokes:13,radical:"艹",word:"蓄须"},{ch:"拒",py:"jù",strokes:7,radical:"扌",word:"拒绝"},{ch:"迫",py:"pò",strokes:8,radical:"辶",word:"被迫"},{ch:"宁",py:"nìng",strokes:5,radical:"宀",word:"宁可"}],
      practice: ["朗读课文。","梅兰芳为什么蓄须？","他宁可怎样也不演出？"],
      think: "梅兰芳的气节是什么？",
    }),
    gardenPage("七", ["识字加油站：气节字--蓄、拒、迫、宁。","字词句运用：用「宁可……也不……」写梅兰芳。","书写提示：注意「蓄」「拒」的结构。","日积月累：别董大--莫愁前路无知己，天下谁人不识君。"], { zhTitle: "出塞", lines: ["秦时明月汉时关，", "万里长征人未还。", "但使龙城飞将在，", "不教胡马度阴山。"] }),

    unitPage("八", "智慧故事", "Wisdom", "西门豹治邺、故事二则。", ["西门豹治邺", "故事二则"]),
    ...lessonPage({
      zhTitle: "西门豹治邺", enTitle: "Ximen Bao Governs Ye", pinyin: "xī mén bào zhì yè",
      passage: [["xī","xī" as any].slice(0,2) as [string,string],["mén","mén" as any].slice(0,2) as [string,string],["bào","bào" as any].slice(0,2) as [string,string],["dào","dào" as any].slice(0,2) as [string,string],["le","le" as any].slice(0,2) as [string,string],["yè","yè" as any].slice(0,2) as [string,string],["xiàn","xiàn" as any].slice(0,2) as [string,string],["。","。"]],
      note: "西门豹到邺县，发现巫婆官绅借「河伯娶媳妇」骗钱害人，他将计就计惩治他们，再兴修水利。智慧、为民。",
      recognize: [{ch:"豹",py:"bào",word:"西门豹"},{ch:"邺",py:"yè",word:"邺县"},{ch:"巫",py:"wū",word:"巫婆"},{ch:"绅",py:"shēn",word:"官绅"}],
      write: [{ch:"豹",py:"bào",strokes:10,radical:"豸",word:"豹子"},{ch:"派",py:"pài",strokes:9,radical:"氵",word:"派人"},{ch:"娶",py:"qǔ",strokes:11,radical:"女",word:"娶亲"},{ch:"媳",py:"xí",strokes:13,radical:"女",word:"媳妇"}],
      practice: ["朗读课文。","西门豹发现什么问题？","他怎么惩治巫婆官绅？"],
      think: "西门豹的办法妙在哪里？",
    }),
    gardenPage("八", ["识字加油站：官职字--豹、派、娶、媳。","字词句运用：用「先……再……」讲西门豹。","书写提示：注意「娶」「媳」的女字旁。","日积月累：扁鹊治病--防微杜渐。"], { zhTitle: "暮江吟", lines: ["一道残阳铺水中，", "半江瑟瑟半江红。", "可怜九月初三夜，", "露似真珠月似弓。"] }),

    strokePage("识字表（会认）", "四年级上册会认字约 250 个。重点：潮、罩、蒙、沸、鹅、卵、俗、跃、繁、昧、坠、荚、豌、僵、苔、蝙、蝠、雷、达、唤、纪、技、索、沌、斧、劈、撑、炎、溺、衔、普、罗、宙、斯、虎、占、铺、匀、宅、慎、择、址、戎、尝、诸、竞、崛、范、魏、谓、拳、膊、蓄、扰、拒、豹、邺、巫、绅。"),
    strokePage("写字表（会写）", "四年级上册会写字约 250 个。重点：潮、称、盐、罩、淘、牵、鹅、卵、繁、漫、灭、藤、豌、按、舒、恐、蝙、蝠、蚊、即、唤、纪、改、程、翻、劈、撑、竭、帝、溺、衔、返、普、罗、悲、惨、虎、占、铺、匀、宅、临、慎、址、戎、尝、诸、竞、肃、晰、振、胸、摸、甚、跪、捶、蓄、拒、迫、宁、豹、派、娶、媳。"),
    strokePage("词语表", "大潮、称为、盐官、笼罩、淘洗、牵手、白鹅、鹅卵石、繁星、漫灭、消灭、藤萝、豌豆、按照、舒服、恐怕、蝙蝠、蚊子、即使、呼唤、世纪、改变、程度、翻身、劈开、撑住、竭力、皇帝、溺水、衔接、返回、普通、罗列、悲惨、老虎、占领、铺开、均匀、住宅、临时、慎重、地址、戎装、品尝、诸位、竞争、严肃、清晰、振奋、胸怀、摸头、甚至、跪下、捶背、蓄须、拒绝、被迫、宁可、豹子、派人、娶亲、媳妇。"),
    { kind: "back", title: { en: "Afterword", zh: "后记" }, body: { en: <>You finished Grade 4 Book One.</>, zh: <>你读完了四年级上册。四年级 · 下册 从这里继续。</> } },
  ],
};
