import type { Book } from "@/components/BookReader";
import { lessonPage, gardenPage, unitPage, poemPage, strokePage } from "./grade1";

// 七年级 · 上册（部编版七年级上册结构）
export const grade7Book: Book = {
  gradeId: "g7",
  title: { en: "Grade 7 · Book One", zh: "七年级 · 上册" },
  subtitle: { en: "Seasons, Family & Classics", zh: "四季、亲情与经典" },
  pages: [
    { kind: "cover", title: { en: "Cover", zh: "封面" } },
    { kind: "copyright", title: { en: "About", zh: "出版说明" }, body: { en: <>Grade 7 Book One, after the PEP seventh-grade textbook.</>, zh: <>《七年级 · 上册》，按部编版七年级上册结构编写。</> } },
    { kind: "toc", title: { en: "Contents", zh: "目录" } },

    unitPage("一", "四季美景", "Four Seasons", "春、济南的冬天、雨的四季。", ["春", "济南的冬天", "雨的四季"]),
    ...lessonPage({
      zhTitle: "春", enTitle: "Spring", pinyin: "chūn",
      passage: [["pàn","盼"],["wàng","望"],["zhe","着"],["，","，"],["pàn","盼"],["wàng","望"],["zhe","着"],["，","，"],["dōng","东"],["fēng","风"],["de","的"],["jiǎo","脚"],["bù","步"],["jìn","近"],["le","了"],["。","。"]],
      note: "朱自清。盼春、绘春（春草、春花、春风、春雨、迎春）、赞春。比喻拟人，语言优美。",
      recognize: [{ch:"嗡",py:"wēng",word:"嗡嗡"},{ch:"朗",py:"lǎng",word:"朗润"},{ch:"润",py:"rùn",word:"朗润"},{ch:"酝",py:"yùn",word:"酝酿"},{ch:"酿",py:"niàng",word:"酝酿"}],
      write: [{ch:"嗡",py:"wēng",strokes:13,radical:"口",word:"嗡嗡"},{ch:"朗",py:"lǎng",strokes:10,radical:"月",word:"朗润"},{ch:"润",py:"rùn",strokes:10,radical:"氵",word:"湿润"},{ch:"酝",py:"yùn",strokes:7,radical:"酉",word:"酝酿"}],
      practice: ["朗读并背诵。","作者绘了哪几幅春景图？","用了哪些修辞？"],
      think: "你心中的春天是什么样？",
    }),
    ...lessonPage({
      zhTitle: "济南的冬天", enTitle: "Winter in Jinan", pinyin: "jǐ nán de dōng tiān",
      passage: [["jǐ","济"],["nán","南"],["de","的"],["dōng","冬"],["tiān","天"],["shì","是"],["wēn","温"],["qíng","晴"],["de","的"],["。","。"]],
      note: "老舍。济南冬天温晴，山、水、城如画。比喻拟人，充满喜爱。",
      recognize: [{ch:"髻",py:"jì",word:"发髻"},{ch:"镶",py:"xiāng",word:"镶边"},{ch:"澄",py:"chéng",word:"澄清"}],
      write: [{ch:"济",py:"jǐ",strokes:9,radical:"氵",word:"济南"},{ch:"髻",py:"jì",strokes:16,radical:"髟",word:"发髻"},{ch:"镶",py:"xiāng",strokes:22,radical:"钅",word:"镶边"},{ch:"澄",py:"chéng",strokes:15,radical:"氵",word:"澄清"}],
      practice: ["朗读课文。","济南冬天有什么特点？","作者怎么写山和水？"],
      think: "济南的冬天为什么是「宝地」？",
    }),
    poemPage("观沧海", "曹操", [["dōng","东"],["lín","临"],["jié","碣"],["shí","石"],["，","，"],["yǐ","以"],["guān","观"],["cāng","沧"],["hǎi","海"],["。","。"],["shuǐ","水"],["hé","何"],["dàn","澹"],["dàn","澹"],["，","，"],["shān","山"],["dǎo","岛"],["sǒng","竦"],["zhì","峙"],["。","。"]], "东临碣石观沧海。水波澹澹，山岛竦峙。", "曹操写大海的壮阔，抒发统一天下的抱负。"),
    gardenPage("一", ["识字加油站：景物字--嗡、朗、润、酝。","字词句运用：用比喻拟人写一季。","书写提示：注意「镶」「澄」的结构。","日积月累：闻王昌龄左迁龙标遥有此寄。"], { zhTitle: "闻王昌龄左迁龙标遥有此寄", lines: ["杨花落尽子规啼，", "闻道龙标过五溪。", "我寄愁心与明月，", "随君直到夜郎西。"] }),

    unitPage("二", "至爱亲情", "Dearest Family", "秋天的怀念、散步、散文诗二首。", ["秋天的怀念", "散步", "金色花"]),
    ...lessonPage({
      zhTitle: "秋天的怀念", enTitle: "Autumn Remembrance", pinyin: "qiū tiān de huái niàn",
      passage: [["shuāng","双"],["tān","瘫"],["huàn","痪"],["hòu","后"],["，","，"],["wǒ","我"],["de","的"],["pí","脾"],["qì","气"],["biàn","变"],["de","得"],["bào","暴"],["nù","怒"],["wú","无"],["cháng","常"],["。","。"]],
      note: "史铁生。瘫痪后我暴怒，母亲隐忍照顾，临终仍挂念儿女。母爱深沉，要好好活。",
      recognize: [{ch:"瘫",py:"tān",word:"瘫痪"},{ch:"痪",py:"huàn",word:"瘫痪"},{ch:"憔",py:"qiáo",word:"憔悴"},{ch:"悴",py:"cuì",word:"憔悴"}],
      write: [{ch:"瘫",py:"tān",strokes:15,radical:"疒",word:"瘫痪"},{ch:"痪",py:"huàn",strokes:12,radical:"疒",word:"瘫痪"},{ch:"憔",py:"qiáo",strokes:15,radical:"忄",word:"憔悴"},{ch:"悴",py:"cuì",strokes:11,radical:"忄",word:"憔悴"}],
      practice: ["朗读课文。","母亲是怎样的人？","「好好活」是什么意思？"],
      think: "你从文中读到怎样的母爱？",
    }),
    ...lessonPage({
      zhTitle: "散步", enTitle: "A Walk", pinyin: "sàn bù",
      passage: [["wǒ","我"],["men","们"],["zài","在"],["tián","田"],["yě","野"],["shàng","上"],["sàn","散"],["bù","步"],["。","。"]],
      note: "莫怀戚。一家四口散步，分歧时我背母亲、妻背儿子。尊老爱幼、中年责任。",
      recognize: [{ch:"熬",py:"áo",word:"熬过"},{ch:"咕",py:"gū",word:"咕咕"},{ch:"粼",py:"lín",word:"波光粼粼"}],
      write: [{ch:"熬",py:"áo",strokes:14,radical:"灬",word:"熬过"},{ch:"信",py:"xìn",strokes:9,radical:"亻",word:"信服"},{ch:"服",py:"fú",strokes:8,radical:"月",word:"信服"},{ch:"拆",py:"chāi",strokes:8,radical:"扌",word:"拆散"}],
      practice: ["朗读课文。","散步中发生了什么分歧？","我怎么解决？"],
      think: "「我背上的同她背上的加起来就是整个世界」怎么理解？",
    }),
    gardenPage("二", ["识字加油站：亲情字--瘫、痪、憔、悴。","字词句运用：用细节写亲情。","书写提示：注意「憔」「悴」的忄旁。","日积月累：游子吟。"], { zhTitle: "次北固山下", lines: ["客路青山外，", "行舟绿水前。", "潮平两岸阔，", "风正一帆悬。"] }),

    unitPage("三", "学习生活", "Learning", "从百草园到三味书屋、再塑生命的人、论语十二章。", ["从百草园到三味书屋", "再塑生命的人", "论语十二章"]),
    ...lessonPage({
      zhTitle: "从百草园到三味书屋", enTitle: "From Baicao Garden to Sanwei Study", pinyin: "cóng bǎi cǎo yuán dào sān wèi shū wū",
      passage: [["wǒ","我"],["jiā","家"],["de","的"],["hòu","后"],["miàn","面"],["yǒu","有"],["yí","一"],["gè","个"],["hěn","很"],["dà","大"],["de","的"],["yuán","园"],["，","，"],["xiāng","相"],["chuán","传"],["jiào","叫"],["zuò","作"],["bǎi","百"],["cǎo","草"],["yuán","园"],["。","。"]],
      note: "鲁迅。百草园是乐园（捕鸟、听故事），三味书屋读书。童年乐趣与成长。",
      recognize: [{ch:"畦",py:"qí",word:"菜畦"},{ch:"皂",py:"zào",word:"皂荚"},{ch:"荚",py:"jiá",word:"皂荚"},{ch:"蟀",py:"shuài",word:"蟋蟀"}],
      write: [{ch:"畦",py:"qí",strokes:11,radical:"田",word:"菜畦"},{ch:"皂",py:"zào",strokes:7,radical:"白",word:"肥皂"},{ch:"荚",py:"jiá",strokes:9,radical:"艹",word:"豆荚"},{ch:"蟀",py:"shuài",strokes:17,radical:"虫",word:"蟋蟀"}],
      practice: ["朗读课文。","百草园有哪些乐趣？","三味书屋生活怎样？"],
      think: "你更喜欢百草园还是三味书屋？",
    }),
    ...lessonPage({
      zhTitle: "论语十二章", enTitle: "Twelve Chapters of the Analects", pinyin: "lún yǔ shí èr zhāng",
      passage: [["zǐ","子"],["yuē","曰"],["：","："],["xué","学"],["ér","而"],["shí","时"],["xí","习"],["zhī","之"],["，","，"],["bù","不"],["yì","亦"],["yuè","说"],["hū","乎"],["？","？"]],
      note: "孔子及弟子。谈学习方法（学而时习之、温故知新）、态度（三人行必有我师）、志向（三军可夺帅）。",
      recognize: [{ch:"愠",py:"yùn",word:"不愠"},{ch:"罔",py:"wǎng",word:"学而不思则罔"},{ch:"殆",py:"dài",word:"思而不学则殆"},{ch:"箪",py:"dān",word:"一箪食"}],
      write: [{ch:"愠",py:"yùn",strokes:12,radical:"忄",word:"不愠"},{ch:"罔",py:"wǎng",strokes:8,radical:"冂",word:"迷罔"},{ch:"殆",py:"dài",strokes:9,radical:"歹",word:"殆尽"},{ch:"箪",py:"dān",strokes:14,radical:"竹",word:"箪食"}],
      practice: ["朗读并背诵。","哪些讲学习方法？哪些讲态度？","选一句谈体会。"],
      think: "「三人行必有我师」对你有什么启发？",
    }),
    gardenPage("三", ["识字加油站：论语字--愠、罔、殆、箪。","字词句运用：用论语名句写学习。","书写提示：注意「愠」「箪」的结构。","日积月累：峨眉山月歌。"], { zhTitle: "天净沙·秋思", lines: ["枯藤老树昏鸦，", "小桥流水人家，", "古道西风瘦马。", "夕阳西下，", "断肠人在天涯。"] }),

    unitPage("四", "人生之舟", "Life's Boat", "纪念白求恩、植树的牧羊人、走一步再走一步、诫子书。", ["纪念白求恩", "植树的牧羊人", "走一步，再走一步", "诫子书"]),
    ...lessonPage({
      zhTitle: "纪念白求恩", enTitle: "In Memory of Norman Bethune", pinyin: "jì niàn bái qiú ēn",
      passage: [["bái","白"],["qiú","求"],["ēn","恩"],["tóng","同"],["zhì","zhì" as any].slice(0,2) as [string,string],["shì","是"],["jiā","加"],["ná","拿"],["dà","大"],["fū","夫"],["yī","医"],["shēng","生"],["。","。"]],
      note: "毛泽东。白求恩毫不利己专门利人、对技术精益求精。纪念他的国际主义精神。",
      recognize: [{ch:"冀",py:"jì",word:"冀中"},{ch:"遣",py:"qiǎn",word:"派遣"},{ch:"殉",py:"xùn",word:"殉职"}],
      write: [{ch:"冀",py:"jì",strokes:16,radical:"八",word:"冀望"},{ch:"遣",py:"qiǎn",strokes:13,radical:"辶",word:"派遣"},{ch:"殉",py:"xùn",strokes:10,radical:"歹",word:"殉职"},{ch:"忱",py:"chén",strokes:7,radical:"忄",word:"热忱"}],
      practice: ["朗读课文。","白求恩有哪些精神？","我们学他什么？"],
      think: "什么是「毫不利己专门利人」？",
    }),
    ...lessonPage({
      zhTitle: "诫子书", enTitle: "A Letter to My Son", pinyin: "jiè zǐ shū",
      passage: [["fú","夫"],["jūn","君"],["zǐ","子"],["zhī","zhī" as any].slice(0,2) as [string,string],["xíng","xíng" as any].slice(0,2) as [string,string],["，","，"],["jìng","jìng" as any].slice(0,2) as [string,string],["yǐ","yǐ" as any].slice(0,2) as [string,string],["xiū","xiū" as any].slice(0,2) as [string,string],["shēn","shēn" as any].slice(0,2) as [string,string],["，","，"],["jiǎn","jiǎn" as any].slice(0,2) as [string,string],["yǐ","yǐ" as any].slice(0,2) as [string,string],["yǎng","yǎng" as any].slice(0,2) as [string,string],["dé","dé" as any].slice(0,2) as [string,string],["。","。"]],
      note: "诸葛亮。静以修身，俭以养德。非淡泊无以明志，非宁静无以致远。劝子修身立志。",
      recognize: [{ch:"诫",py:"jiè",word:"告诫"},{ch:"淡泊",py:"dàn bó",word:"淡泊"},{ch:"致",py:"zhì",word:"致远"},{ch:"庐",py:"lú",word:"茅庐"}],
      write: [{ch:"诫",py:"jiè",strokes:9,radical:"讠",word:"告诫"},{ch:"淡",py:"dàn",strokes:11,radical:"氵",word:"淡泊"},{ch:"泊",py:"bó",strokes:8,radical:"氵",word:"淡泊"},{ch:"致",py:"zhì",strokes:10,radical:"至",word:"致远"}],
      practice: ["朗读并背诵。","诸葛亮劝儿子什么？","「静」「俭」为什么重要？"],
      think: "「非宁静无以致远」对你有什么启发？",
    }),
    gardenPage("四", ["识字加油站：修身字--诫、淡、泊、致。","字词句运用：用「非……无以……」造句。","书写提示：注意「诫」「致」的结构。","日积月累：秋词。"], { zhTitle: "秋词", lines: ["自古逢秋悲寂寥，", "我言秋日胜春朝。", "晴空一鹤排云上，", "便引诗情到碧霄。"] }),

    unitPage("五", "动物与人", "Animals & Humans", "猫、动物笑谈、狼。", ["猫", "动物笑谈", "狼"]),
    ...lessonPage({
      zhTitle: "猫", enTitle: "The Cat", pinyin: "māo",
      passage: [["wǒ","wǒ" as any].slice(0,2) as [string,string],["jiā","jiā" as any].slice(0,2) as [string,string],["yǎng","yǎng" as any].slice(0,2) as [string,string],["guò","guò" as any].slice(0,2) as [string,string],["sān","sān" as any].slice(0,2) as [string,string],["zhī","zhī" as any].slice(0,2) as [string,string],["māo","māo" as any].slice(0,2) as [string,string],["。","。"]],
      note: "郑振铎。三次养猫，第三只被冤枉后死去，我永无改正的机会。不要主观臆断、要公正。",
      recognize: [{ch:"逗",py:"dòu",word:"逗弄"},{ch:"缕",py:"lǚ",word:"一缕"},{ch:"怅",py:"chàng",word:"怅然"}],
      write: [{ch:"逗",py:"dòu",strokes:10,radical:"辶",word:"逗弄"},{ch:"缕",py:"lǚ",strokes:12,radical:"纟",word:"一缕"},{ch:"怅",py:"chàng",strokes:7,radical:"忄",word:"怅然"},{ch:"诅",py:"zǔ",strokes:8,radical:"讠",word:"诅咒"}],
      practice: ["朗读课文。","三只猫各有什么结局？","我为什么难过？"],
      think: "你冤枉过别人吗？",
    }),
    ...lessonPage({
      zhTitle: "狼", enTitle: "The Wolf", pinyin: "láng",
      passage: [["yì","yì" as any].slice(0,2) as [string,string],["tú","tú" as any].slice(0,2) as [string,string],["wǎn","wǎn" as any].slice(0,2) as [string,string],["guī","guī" as any].slice(0,2) as [string,string],["，","，"],["dān","dān" as any].slice(0,2) as [string,string],["zhōng","zhōng" as any].slice(0,2) as [string,string],["dàn","dàn" as any].slice(0,2) as [string,string],["r","肉"].slice(0,2) as [string,string],["。","。"]],
      note: "蒲松龄。屠户遇狼、惧狼、御狼、杀狼。狼狡猾但终被杀。禽兽之变诈几何哉。",
      recognize: [{ch:"窘",py:"jiǒng",word:"窘迫"},{ch:"苫",py:"shàn",word:"苫蔽"},{ch:"瞑",py:"míng",word:"瞑目"},{ch:"隧",py:"suì",word:"隧入"}],
      write: [{ch:"窘",py:"jiǒng",strokes:12,radical:"穴",word:"窘迫"},{ch:"苫",py:"shàn",strokes:8,radical:"艹",word:"苫蔽"},{ch:"瞑",py:"míng",strokes:15,radical:"目",word:"瞑目"},{ch:"隧",py:"suì",strokes:14,radical:"阝",word:"隧道"}],
      practice: ["朗读并背诵。","屠户怎么战胜狼？","狼的形象是什么？"],
      think: "「禽兽之变诈几何哉」说明什么？",
    }),
    gardenPage("五", ["识字加油站：动物字--逗、缕、怅、诅。","字词句运用：用动作写动物。","书写提示：注意「窘」「隧」的结构。","日积月累：十一月四日风雨大作。"], { zhTitle: "十一月四日风雨大作", lines: ["僵卧孤村不自哀，", "尚思为国戍轮台。", "夜阑卧听风吹雨，", "铁马冰河入梦来。"] }),

    unitPage("六", "想象之翼", "Wings of Imagination", "皇帝的新装、天上的街市、女娲造人、寓言四则。", ["皇帝的新装", "天上的街市", "女娲造人", "寓言四则"]),
    ...lessonPage({
      zhTitle: "皇帝的新装", enTitle: "The Emperor's New Clothes", pinyin: "huáng dì de xīn zhuāng",
      passage: [["xǔ","xǔ" as any].slice(0,2) as [string,string],["duō","duō" as any].slice(0,2) as [string,string],["nián","nián" as any].slice(0,2) as [string,string],["yǐ","yǐ" as any].slice(0,2) as [string,string],["qián","qián" as any].slice(0,2) as [string,string],["，","，"],["yǒu","yǒu" as any].slice(0,2) as [string,string],["yí","yí" as any].slice(0,2) as [string,string],["wèi","wèi" as any].slice(0,2) as [string,string],["huáng","huáng" as any].slice(0,2) as [string,string],["dì","dì" as any].slice(0,2) as [string,string],["。","。"]],
      note: "安徒生。骗子说新装愚蠢的人看不见，大家都不敢说真话，小孩说出真相。讽刺虚伪，赞美天真。",
      recognize: [{ch:"陛",py:"bì",word:"陛下"},{ch:"赐",py:"cì",word:"赏赐"},{ch:"御",py:"yù",word:"御聘"},{ch:"蠢",py:"chǔn",word:"愚蠢"}],
      write: [{ch:"陛",py:"bì",strokes:9,radical:"阝",word:"陛下"},{ch:"赐",py:"cì",strokes:12,radical:"贝",word:"赏赐"},{ch:"御",py:"yù",strokes:12,radical:"彳",word:"防御"},{ch:"蠢",py:"chǔn",strokes:21,radical:"虫",word:"愚蠢"}],
      practice: ["朗读课文。","为什么大家都不敢说真话？","小孩为什么能说？"],
      think: "这童话讽刺什么？",
    }),
    ...lessonPage({
      zhTitle: "天上的街市", enTitle: "The Market in the Sky", pinyin: "tiān shàng de jiē shì",
      passage: [["yuǎn","yuǎn" as any].slice(0,2) as [string,string],["yuǎn","yuǎn" as any].slice(0,2) as [string,string],["de","de" as any].slice(0,2) as [string,string],["jiē","jiē" as any].slice(0,2) as [string,string],["dēng","dēng" as any].slice(0,2) as [string,string],["míng","míng" as any].slice(0,2) as [string,string],["le","le" as any].slice(0,2) as [string,string],["，","，"],["hǎo","hǎo" as any].slice(0,2) as [string,string],["xiàng","xiàng" as any].slice(0,2) as [string,string],["wú","wú" as any].slice(0,2) as [string,string],["shù","shù" as any].slice(0,2) as [string,string],["de","de" as any].slice(0,2) as [string,string],["míng","míng" as any].slice(0,2) as [string,string],["xīng","xīng" as any].slice(0,2) as [string,string],["。","。"]],
      note: "郭沫若。由街灯联想明星，想象天上的街市、牛郎织女自由幸福。表达对美好生活的向往。",
      recognize: [{ch:"缥",py:"piāo",word:"缥缈"},{ch:"缈",py:"miǎo",word:"缥缈"},{ch:"笼",py:"lǒng",word:"笼罩"}],
      write: [{ch:"缥",py:"piāo",strokes:14,radical:"纟",word:"缥缈"},{ch:"缈",py:"miǎo",strokes:12,radical:"纟",word:"缥缈"},{ch:"笼",py:"lóng",strokes:11,radical:"竹",word:"灯笼"},{ch:"罩",py:"zhào",strokes:13,radical:"罒",word:"笼罩"}],
      practice: ["朗读并背诵。","诗人由什么联想到什么？","天上的牛郎织女怎样？"],
      think: "诗人为什么这样想象？",
    }),
    gardenPage("六", ["识字加油站：想象字--缥、缈、笼、罩。","字词句运用：用联想想象写星空。","书写提示：注意「缥」「缈」的纟旁。","日积月累：潼关怀古。"], { zhTitle: "潼关怀古", lines: ["峰峦如聚，波涛如怒，", "山河表里潼关路。", "望西都，意踌躇。", "兴，百姓苦；亡，百姓苦。"] }),

    strokePage("识字表（会认）", "七年级上册会认字约 160 个。重点：嗡、朗、润、酝、酿、髻、镶、澄、瘫、痪、憔、悴、熬、咕、粼、畦、皂、荚、蟀、愠、罔、殆、箪、冀、遣、殉、忱、诫、淡泊、致、逗、缕、怅、诅、窘、苫、瞑、隧、陛、赐、御、蠢、缥、缈、笼、罩。"),
    strokePage("写字表（会写）", "七年级上册会写字约 160 个。重点：嗡、朗、润、酝、济、髻、镶、澄、瘫、痪、憔、悴、熬、信、服、拆、畦、皂、荚、蟀、愠、、殆、箪、冀、遣、殉、忱、诫、淡、泊、致、逗、缕、怅、诅、窘、苫、瞑、隧、陛、赐、御、蠢、缥、缈、笼、罩。"),
    strokePage("词语表", "嗡嗡、朗润、湿润、酝酿、济南、发髻、镶边、澄清、瘫痪、憔悴、熬过、信服、拆散、菜畦、肥皂、豆荚、蟋蟀、不愠、迷罔、殆尽、箪食、冀望、派遣、殉职、热忱、告诫、淡泊、致远、逗弄、一缕、怅然、诅咒、窘迫、苫蔽、瞑目、隧道、陛下、赏赐、防御、愚蠢、缥缈、灯笼、笼罩。"),
    { kind: "back", title: { en: "Afterword", zh: "后记" }, body: { en: <>You finished Grade 7 Book One.</>, zh: <>你读完了七年级上册。七年级 · 下册 从这里继续。</> } },
  ],
};
