import type { Book } from "@/components/BookReader";
import { lessonPage, gardenPage, speakPage, unitPage, poemPage, strokePage } from "./grade1";

// 五年级 · 上册（部编版五年级上册结构）
export const grade5Book: Book = {
  gradeId: "g5",
  title: { en: "Grade 5 · Book One", zh: "五年级 · 上册" },
  subtitle: { en: "Things, People & Country", zh: "万物、人物与家国" },
  pages: [
    { kind: "cover", title: { en: "Cover", zh: "封面" } },
    { kind: "copyright", title: { en: "About", zh: "出版说明" }, body: { en: <>Grade 5 Book One, after the PEP fifth-grade textbook.</>, zh: <>《五年级 · 上册》，按部编版五年级上册结构编写。</> } },
    { kind: "toc", title: { en: "Contents", zh: "目录" } },

    unitPage("一", "万物有灵", "All Things Have Spirit", "白鹭、落花生、桂花雨。", ["白鹭", "落花生", "桂花雨"]),
    ...lessonPage({
      zhTitle: "白鹭", enTitle: "The Egret", pinyin: "bái lù",
      passage: [["bái","白"],["lù","鹭"],["shì","是"],["yì","一"],["shǒu","首"],["jīng","精"],["qiǎo","巧"],["de","的"],["shī","诗"],["。","。"]],
      note: "郭沫若。白鹭色素的配合、身段的大小都适宜，是一首精巧的诗、一首韵在骨子里的散文诗。",
      recognize: [{ch:"鹭",py:"lù",word:"白鹭"},{ch:"嫌",py:"xián",word:"嫌弃"},{ch:"喙",py:"huì",word:"长喙"},{ch:"黛",py:"dài",word:"黛色"}],
      write: [{ch:"宜",py:"yí",strokes:8,radical:"宀",word:"适宜"},{ch:"鹤",py:"hè",strokes:15,radical:"隹",word:"白鹤"},{ch:"嫌",py:"xián",strokes:13,radical:"女",word:"嫌弃"},{ch:"韵",py:"yùn",strokes:13,radical:"音",word:"韵味"}],
      practice: ["朗读课文，背诵。","白鹭的美在哪里？","为什么说它是一首诗？"],
      think: "你见过什么像诗的动物？",
    }),
    ...lessonPage({
      zhTitle: "落花生", enTitle: "The Peanut", pinyin: "luò huā shēng",
      passage: [["wǒ","wǒ" as any].slice(0,2) as [string,string],["men","men" as any].slice(0,2) as [string,string],["jiā","jiā" as any].slice(0,2) as [string,string],["de","de" as any].slice(0,2) as [string,string],["hòu","hòu" as any].slice(0,2) as [string,string],["y","园"].slice(0,2) as [string,string],["yǒu","yǒu" as any].slice(0,2) as [string,string],["bàn","bàn" as any].slice(0,2) as [string,string],["mǔ","mǔ" as any].slice(0,2) as [string,string],["kōng","kōng" as any].slice(0,2) as [string,string],["dì","dì" as any].slice(0,2) as [string,string],["。","。"]],
      note: "许地山。一家人议花生：花生不好看但有用。要做有用的人，不要做只讲体面的人。",
      recognize: [{ch:"亩",py:"mǔ",word:"半亩"},{ch:"吩",py:"fēn",word:"吩咐"},{ch:"咐",py:"fù",word:"吩咐"},{ch:"榨",py:"zhà",word:"榨油"}],
      write: [{ch:"亩",py:"mǔ",strokes:7,radical:"亠",word:"半亩"},{ch:"播",py:"bō",strokes:15,radical:"扌",word:"播种"},{ch:"吩",py:"fēn",strokes:7,radical:"口",word:"吩咐"},{ch:"榨",py:"zhà",strokes:14,radical:"木",word:"榨油"}],
      practice: ["朗读课文。","花生的好处是什么？","父亲希望我们做怎样的人？"],
      think: "你想做花生还是苹果那样的人？",
    }),
    ...lessonPage({
      zhTitle: "桂花雨", enTitle: "Osmanthus Rain", pinyin: "guì huā yǔ",
      passage: [["zhōng","zhōng" as any].slice(0,2) as [string,string],["qiū","qiū" as any].slice(0,2) as [string,string],["shí","shí" as any].slice(0,2) as [string,string],["jié","jié" as any].slice(0,2) as [string,string],["，","，"],["z","最"].slice(0,2) as [string,string],["rèn","rèn" as any].slice(0,2) as [string,string],["r","人"].slice(0,2) as [string,string],["xǐ","xǐ" as any].slice(0,2) as [string,string],["huan","欢"].slice(0,2) as [string,string],["de","de" as any].slice(0,2) as [string,string],["shì","shì" as any].slice(0,2) as [string,string],["y","摇"].slice(0,2) as [string,string],["guì","guì" as any].slice(0,2) as [string,string],["huā","huā" as any].slice(0,2) as [string,string],["。","。"]],
      note: "琦君。摇桂花时桂花纷纷落下像下雨。童年的快乐和对故乡的思念。",
      recognize: [{ch:"桂",py:"guì",word:"桂花"},{ch:"箩",py:"luó",word:"箩筐"},{ch:"杭",py:"háng",word:"杭州"}],
      write: [{ch:"懂",py:"dǒng",strokes:15,radical:"忄",word:"懂得"},{ch:"兰",py:"lán",strokes:5,radical:"丷",word:"兰花"},{ch:"箩",py:"luó",strokes:14,radical:"竹",word:"箩筐"},{ch:"婆",py:"pó",strokes:11,radical:"女",word:"外婆"}],
      practice: ["朗读课文。","摇桂花是什么感觉？","为什么难忘桂花雨？"],
      think: "你童年最难忘的是什么？",
    }),
    speakPage("制定班级公约", "讨论并制定班级公约，人人参与。", ["说清楚公约内容。", "听取大家意见。"], ["上课认真听讲。", "不乱扔垃圾。", "同学互相帮助。"]),
    gardenPage("一", ["识字加油站：花鸟字--鹭、桂、兰、箩。","字词句运用：用对比写一种事物。","书写提示：注意「播」「榨」的结构。","日积月累：蝉--垂緌饮清露，流响出疏桐。"], { zhTitle: "蝉", lines: ["垂緌饮清露，", "流响出疏桐。", "居高声自远，", "非是藉秋风。"] }),

    unitPage("二", "阅读速度", "Reading Speed", "搭石、将相和、什么比猎豹的速度更快。", ["搭石", "将相和", "什么比猎豹的速度更快"]),
    ...lessonPage({
      zhTitle: "搭石", enTitle: "The Stepping Stones", pinyin: "dā shí",
      passage: [["jìn","jìn" as any].slice(0,2) as [string,string],["rù","rù" as any].slice(0,2) as [string,string],["qiū","qiū" as any].slice(0,2) as [string,string],["tiān","tiān" as any].slice(0,2) as [string,string],["，","，"],["r","人"].slice(0,2) as [string,string],["men","men" as any].slice(0,2) as [string,string],["chū","chū" as any].slice(0,2) as [string,string],["gōng","gōng" as any].slice(0,2) as [string,string],["b","必"].slice(0,2) as [string,string],["bèi","bèi" as any].slice(0,2) as [string,string],["dā","dā" as any].slice(0,2) as [string,string],["shí","shí" as any].slice(0,2) as [string,string],["。","。"]],
      note: "乡亲们摆搭石、走搭石，互相谦让、背老人过河。搭石联结着乡亲们的感情。",
      recognize: [{ch:"汛",py:"xùn",word:"汛期"},{ch:"访",py:"fǎng",word:"访友"},{ch:"鞋",py:"xié",word:"脱鞋"},{ch:"挽",py:"wǎn",word:"挽裤"}],
      write: [{ch:"汛",py:"xùn",strokes:6,radical:"氵",word:"汛期"},{ch:"访",py:"fǎng",strokes:6,radical:"讠",word:"访问"},{ch:"鞋",py:"xié",strokes:15,radical:"革",word:"鞋子"},{ch:"挽",py:"wǎn",strokes:10,radical:"扌",word:"挽手"}],
      practice: ["提高速度默读课文。","人们怎么摆搭石、走搭石？","搭石联结着什么？"],
      think: "你从搭石看出乡亲们什么品质？",
    }),
    ...lessonPage({
      zhTitle: "将相和", enTitle: "The General and the Minister", pinyin: "jiàng xiàng hé",
      passage: [["zhàn","zhàn" as any].slice(0,2) as [string,string],["guó","guó" as any].slice(0,2) as [string,string],["shí","shí" as any].slice(0,2) as [string,string],["q","期"].slice(0,2) as [string,string],["，","，"],["qín","qín" as any].slice(0,2) as [string,string],["guó","guó" as any].slice(0,2) as [string,string],["zuì","zuì" as any].slice(0,2) as [string,string],["qiáng","qiáng" as any].slice(0,2) as [string,string],["d","大"].slice(0,2) as [string,string],["。","。"]],
      note: "完璧归赵、渑池之会、负荆请罪三个故事。蔺相如以国家利益为重，廉颇知错就改，将相和好。",
      recognize: [{ch:"璧",py:"bì",word:"和氏璧"},{ch:"臣",py:"chén",word:"大臣"},{ch:"蔺",py:"lìn",word:"蔺相如"},{ch:"颇",py:"pō",word:"廉颇"}],
      write: [{ch:"召",py:"zhào",strokes:5,radical:"口",word:"召集"},{ch:"臣",py:"chén",strokes:6,radical:"臣",word:"大臣"},{ch:"议",py:"yì",strokes:5,radical:"讠",word:"议论"},{ch:"献",py:"xiàn",strokes:13,radical:"犬",word:"献出"}],
      practice: ["快速默读。","三个小故事各讲什么？","将相为什么和好？"],
      think: "蔺相如和廉颇各有什么品质？",
    }),
    gardenPage("二", ["识字加油站：历史字--璧、臣、蔺、颇。","字词句运用：用「因为……所以……」说将相和。","书写提示：注意「献」「议」的结构。","日积月累：不饱食以终日，不弃功于寸阴。"], { zhTitle: "示儿", lines: ["死去元知万事空，", "但悲不见九州同。", "王师北定中原日，", "家祭无忘告乃翁。"] }),

    unitPage("三", "民间故事", "Folk Tales", "猎人海力布、牛郎织女。", ["猎人海力布", "牛郎织女"]),
    ...lessonPage({
      zhTitle: "猎人海力布", enTitle: "The Hunter Hailibu", pinyin: "liè rén hǎi lì bù",
      passage: [["cóng","cóng" as any].slice(0,2) as [string,string],["qián","qián" as any].slice(0,2) as [string,string],["y","有"].slice(0,2) as [string,string],["g","个"].slice(0,2) as [string,string],["liè","liè" as any].slice(0,2) as [string,string],["r","人"].slice(0,2) as [string,string],["，","，"],["míng","míng" as any].slice(0,2) as [string,string],["jiào","jiào" as any].slice(0,2) as [string,string],["h","海"].slice(0,2) as [string,string],["l","力"].slice(0,2) as [string,string],["b","布"].slice(0,2) as [string,string],["。","。"]],
      note: "海力布救了龙王得宝石，能听动物说话，但不能告诉人，否则变石头。他为救乡亲说出秘密，变成石头。舍己为人。",
      recognize: [{ch:"猎",py:"liè",word:"猎人"},{ch:"酬",py:"chóu",word:"酬谢"},{ch:"珍",py:"zhēn",word:"珍宝"},{ch:"叮",py:"dīng",word:"叮嘱"}],
      write: [{ch:"猎",py:"liè",strokes:11,radical:"犭",word:"打猎"},{ch:"酬",py:"chóu",strokes:13,radical:"酉",word:"酬谢"},{ch:"珍",py:"zhēn",strokes:9,radical:"王",word:"珍贵"},{ch:"叮",py:"dīng",strokes:5,radical:"口",word:"叮嘱"}],
      practice: ["朗读课文。","海力布怎么得宝石？","他为什么变石头？"],
      think: "海力布值得吗？",
    }),
    ...lessonPage({
      zhTitle: "牛郎织女", enTitle: "The Cowherd and the Weaver Girl", pinyin: "niú láng zhī nǚ",
      passage: [["g","古"].slice(0,2) as [string,string],["shí","shí" as any].slice(0,2) as [string,string],["hou","候"].slice(0,2) as [string,string],["y","有"].slice(0,2) as [string,string],["g","个"].slice(0,2) as [string,string],["hái","hái" as any].slice(0,2) as [string,string],["zi","子"].slice(0,2) as [string,string],["，","，"],["míng","míng" as any].slice(0,2) as [string,string],["jiào","jiào" as any].slice(0,2) as [string,string],["niú","niú" as any].slice(0,2) as [string,string],["l","郎"].slice(0,2) as [string,string],["。","。"]],
      note: "牛郎和织女相爱，被王母拆散，每年七夕鹊桥相会。追求自由幸福。",
      recognize: [{ch:"郎",py:"láng",word:"牛郎"},{ch:"爹",py:"diē",word:"爹娘"},{ch:"嫂",py:"sǎo",word:"嫂子"},{ch:"恳",py:"kěn",word:"勤恳"}],
      write: [{ch:"郎",py:"láng",strokes:8,radical:"阝",word:"牛郎"},{ch:"爹",py:"diē",strokes:10,radical:"父",word:"爹爹"},{ch:"嫂",py:"sǎo",strokes:12,radical:"女",word:"嫂子"},{ch:"辆",py:"liàng",strokes:11,radical:"车",word:"一辆"}],
      practice: ["朗读课文。","牛郎和织女怎么相识？","王母为什么拆散他们？"],
      think: "七夕鹊桥相会表达什么愿望？",
    }),
    gardenPage("三", ["识字加油站：民间故事--海力布、牛郎织女、孟姜女、梁祝。","字词句运用：复述故事。","书写提示：注意「酬」「嫂」的结构。","日积月累：乞巧--七夕今宵看碧霄，牵牛织女渡河桥。"], { zhTitle: "乞巧", lines: ["七夕今宵看碧霄，", "牵牛织女渡河桥。", "家家乞巧望秋月，", "穿尽红丝几万条。"] }),

    unitPage("四", "家国情怀", "Patriotism", "少年中国说、圆明园的毁灭、小岛。", ["少年中国说", "圆明园的毁灭", "小岛"]),
    ...lessonPage({
      zhTitle: "少年中国说", enTitle: "Ode to Young China", pinyin: "shào nián zhōng guó shuō",
      passage: [["g","故"].slice(0,2) as [string,string],["jīn","jīn" as any].slice(0,2) as [string,string],["r","之"].slice(0,2) as [string,string],["z","责"].slice(0,2) as [string,string],["r","任"].slice(0,2) as [string,string],["，","，"],["b","不"], ["z","在"], ["t","他"], ["r","人"], ["，","，"],["ér","而"], ["quán","全"], ["z","在"], ["w","我"], ["shào","少"], ["nián","年"], ["。","。"]],
      note: "梁启超。少年智则国智，少年强则国强。少年的责任与中国的前途。",
      recognize: [{ch:"哉",py:"zāi",word:"壮哉"},{ch:"渊",py:"yuān",word:"深渊"},{ch:"鳞",py:"lín",word:"鳞爪"}],
      write: [{ch:"泻",py:"xiè",strokes:8,radical:"氵",word:"泻下"},{ch:"潜",py:"qián",strokes:15,radical:"氵",word:"潜龙"},{ch:"试",py:"shì",strokes:8,radical:"讠",word:"试验"},{ch:"胎",py:"tāi",strokes:9,radical:"月",word:"胎生"}],
      practice: ["朗读并背诵。","少年中国说讲了什么？","少年的责任是什么？"],
      think: "你能为中国做什么？",
    }),
    ...lessonPage({
      zhTitle: "圆明园的毁灭", enTitle: "The Ruins of Yuanmingyuan", pinyin: "yuán míng yuán de huǐ miè",
      passage: [["yuán","yuán" as any].slice(0,2) as [string,string],["míng","míng" as any].slice(0,2) as [string,string],["yuán","yuán" as any].slice(0,2) as [string,string],["de","de" as any].slice(0,2) as [string,string],["huǐ","huǐ" as any].slice(0,2) as [string,string],["miè","miè" as any].slice(0,2) as [string,string],["，","，"],["shì","shì" as any].slice(0,2) as [string,string],["zhōng","zhōng" as any].slice(0,2) as [string,string],["guó","guó" as any].slice(0,2) as [string,string],["wén","wén" as any].slice(0,2) as [string,string],["huà","huà" as any].slice(0,2) as [string,string],["shǐ","shǐ" as any].slice(0,2) as [string,string],["shàng","shàng" as any].slice(0,2) as [string,string],["bù","bù" as any].slice(0,2) as [string,string],["k","可"], ["m","磨"], ["miè","灭"], ["de","的"], ["s","损"], ["shī","失"], ["。","。"]],
      note: "圆明园曾是万园之园，被英法联军毁灭。勿忘国耻，振兴中华。",
      recognize: [{ch:"殿",py:"diàn",word:"殿堂"},{ch:"珑",py:"lóng",word:"玲珑"},{ch:"剔",py:"tī",word:"剔透"},{ch:"烬",py:"jìn",word:"灰烬"}],
      write: [{ch:"毁",py:"huǐ",strokes:13,radical:"殳",word:"毁灭"},{ch:"估",py:"gū",strokes:7,radical:"亻",word:"估计"},{ch:"拱",py:"gǒng",strokes:9,radical:"扌",word:"拱桥"},{ch:"辉",py:"huī",strokes:12,radical:"光",word:"辉煌"}],
      practice: ["朗读课文。","圆明园曾经多辉煌？","它是怎么毁灭的？"],
      think: "为什么说不可估量的损失？",
    }),
    gardenPage("四", ["识字加油站：爱国字--毁、殿、烬、辉。","字词句运用：用「不但……还……」写圆明园。","书写提示：注意「毁」「辉」的结构。","日积月累：太平御览--居安思危，戒奢以俭。"], { zhTitle: "己亥杂诗", lines: ["九州生气恃风雷，", "万马齐喑究可哀。", "我劝天公重抖擞，", "不拘一格降人材。"] }),

    unitPage("五", "说明文", "Expository Writing", "太阳、松鼠。", ["太阳", "松鼠"]),
    ...lessonPage({
      zhTitle: "太阳", enTitle: "The Sun", pinyin: "tài yáng",
      passage: [["y","有"], ["g","个"], ["t","太"], ["y","阳"], ["，","，"],["l","离"], ["w","我"], ["men","们"], ["h","很"], ["yuǎn","远"], ["。","。"]],
      note: "说明文。太阳远、大、热，与人类关系密切。用列数字、作比较、打比方说明。",
      recognize: [{ch:"摄",py:"shè",word:"摄氏"},{ch:"氏",py:"shì",word:"摄氏"},{ch:"殖",py:"zhí",word:"繁殖"},{ch:"粮",py:"liáng",word:"粮食"}],
      write: [{ch:"摄",py:"shè",strokes:13,radical:"扌",word:"摄氏"},{ch:"氏",py:"shì",strokes:4,radical:"氏",word:"姓氏"},{ch:"殖",py:"zhí",strokes:12,radical:"歹",word:"繁殖"},{ch:"粮",py:"liáng",strokes:13,radical:"米",word:"粮食"}],
      practice: ["默读课文。","太阳有什么特点？","用了哪些说明方法？"],
      think: "太阳和人类有什么关系？",
    }),
    ...lessonPage({
      zhTitle: "松鼠", enTitle: "The Squirrel", pinyin: "sōng shǔ",
      passage: [["sōng","sōng" as any].slice(0,2) as [string,string],["shǔ","shǔ" as any].slice(0,2) as [string,string],["shì","shì" as any].slice(0,2) as [string,string],["y","一"], ["zhǒng","种"], ["piào","漂"], ["liang","亮"], ["de","的"], ["xiǎo","小"], ["dòng","动"], ["wù","物"], ["。","。"]],
      note: "布封。松鼠漂亮、驯良、乖巧。文艺性说明文，语言生动。",
      recognize: [{ch:"驯",py:"xùn",word:"驯良"},{ch:"栗",py:"lì",word:"榛栗"},{ch:"缨",py:"yīng",word:"帽缨"}],
      write: [{ch:"鼠",py:"shǔ",strokes:13,radical:"鼠",word:"松鼠"},{ch:"秀",py:"xiù",strokes:7,radical:"禾",word:"秀丽"},{ch:"玲",py:"líng",strokes:9,radical:"王",word:"玲珑"},{ch:"珑",py:"lóng",strokes:9,radical:"王",word:"玲珑"}],
      practice: ["默读课文。","松鼠有什么特点？","语言生动在哪里？"],
      think: "和《太阳》比，写法有什么不同？",
    }),
    gardenPage("五", ["识字加油站：说明方法--列数字、作比较、打比方。","字词句运用：用说明方法介绍一种动物。","书写提示：注意「鼠」「玲」的结构。","日积月累：渔歌子--西塞山前白鹭飞，桃花流水鳜鱼肥。"], { zhTitle: "渔歌子", lines: ["西塞山前白鹭飞，", "桃花流水鳜鱼肥。", "青箬笠，绿蓑衣，", "斜风细雨不须归。"] }),

    unitPage("六", "舐犊情深", "Parental Love", "慈母情深、父爱之舟。", ["慈母情深", "父爱之舟"]),
    ...lessonPage({
      zhTitle: "慈母情深", enTitle: "A Mother's Deep Love", pinyin: "cí mǔ qíng shēn",
      passage: [["w","我"], ["y","一"], ["zhí","直"], ["xiǎng","想"], ["m","买"], ["y","一"], ["b","本"], ["xiǎo","小"], ["shuō","说"], ["shū","书"], ["。","。"]],
      note: "梁晓声。母亲在恶劣环境辛苦工作，仍给钱让我买书。母爱深沉。",
      recognize: [{ch:"魄",py:"pò",word:"魄力"},{ch:"抑",py:"yì",word:"压抑"},{ch:"颓",py:"tuí",word:"颓败"}],
      write: [{ch:"辞",py:"cí",strokes:13,radical:"辛",word:"辞退"},{ch:"抑",py:"yì",strokes:7,radical:"扌",word:"抑制"},{ch:"碌",py:"lù",strokes:13,radical:"石",word:"忙碌"},{ch:"噪",py:"zào",strokes:16,radical:"口",word:"噪音"}],
      practice: ["朗读课文。","母亲工作环境怎样？","母亲为什么给钱买书？"],
      think: "你从哪感受到母爱？",
    }),
    gardenPage("六", ["识字加油站：亲情字--慈、魄、抑、碌。","字词句运用：用细节写父母的爱。","书写提示：注意「碌」「噪」的结构。","日积月累：劝学--黑发不知勤学早，白首方悔读书迟。"], { zhTitle: "观书有感", lines: ["半亩方塘一鉴开，", "天光云影共徘徊。", "问渠那得清如许？", "为有源头活水来。"] }),

    unitPage("七", "四时景物", "Four Seasons", "四季之美、鸟的天堂、月迹。", ["四季之美", "鸟的天堂", "月迹"]),
    ...lessonPage({
      zhTitle: "四季之美", enTitle: "The Beauty of Four Seasons", pinyin: "sì jì zhī měi",
      passage: [["chūn","chūn" as any].slice(0,2) as [string,string],["tiān","tiān" as any].slice(0,2) as [string,string],["zuì","zuì" as any].slice(0,2) as [string,string],["m","美"], ["shì","是"], ["l","黎"], ["míng","明"], ["。","。"]],
      note: "清少纳言。春天最美是黎明，夏天最美是夜晚，秋天最美是黄昏，冬天最美是早晨。细腻感受。",
      recognize: [{ch:"窠",py:"kē",word:"窠里"},{ch:"旷",py:"kuàng",word:"旷野"},{ch:"怡",py:"yí",word:"怡然"}],
      write: [{ch:"黎",py:"lí",strokes:15,radical:"黍",word:"黎明"},{ch:"晕",py:"yùn",strokes:10,radical:"日",word:"红晕"},{ch:"漆",py:"qī",strokes:14,radical:"氵",word:"漆黑"},{ch:"幕",py:"mù",strokes:13,radical:"巾",word:"夜幕"}],
      practice: ["朗读课文，背诵。","四季各最美在什么时候？","作者感受细腻在哪？"],
      think: "你觉得哪个季节最美？",
    }),
    ...lessonPage({
      zhTitle: "鸟的天堂", enTitle: "The Birds' Paradise", pinyin: "niǎo de tiān táng",
      passage: [["w","我"], ["men","们"], ["pāi","拍"], ["z","着"], ["p","掌"], ["h","划"], ["q","去"], ["。","。"]],
      note: "巴金。第一次傍晚只见大榕树，第二次早晨见群鸟。大榕树是鸟的天堂。",
      recognize: [{ch:"桨",py:"jiǎng",word:"船桨"},{ch:"榕",py:"róng",word:"榕树"},{ch:"耀",py:"yào",word:"照耀"}],
      write: [{ch:"桨",py:"jiǎng",strokes:10,radical:"木",word:"船桨"},{ch:"榕",py:"róng",strokes:14,radical:"木",word:"榕树"},{ch:"耀",py:"yào",strokes:20,radical:"光",word:"照耀"},{ch:"暇",py:"xiá",strokes:13,radical:"日",word:"应接不暇"}],
      practice: ["朗读课文。","两次去看到什么不同？","为什么说是鸟的天堂？"],
      think: "你心中的天堂是什么样？",
    }),
    gardenPage("七", ["识字加油站：景物字--黎、晕、漆、幕。","字词句运用：用动态描写写一处景。","书写提示：注意「耀」「暇」的结构。","日积月累：长相思--山一程，水一程，身向榆关那畔行。"], { zhTitle: "长相思", lines: ["山一程，水一程，", "身向榆关那畔行，", "夜深千帐灯。", "风一更，雪一更，", "聒碎乡心梦不成，", "故园无此声。"] }),

    unitPage("八", "读书明智", "Reading Wisely", "古人谈读书、忆读书。", ["古人谈读书", "忆读书"]),
    ...lessonPage({
      zhTitle: "古人谈读书", enTitle: "The Ancients on Reading", pinyin: "gǔ rén tán dú shū",
      passage: [["m","敏"], ["ér","而"], ["h","好"], ["xué","学"], ["，","，"],["b","不"], ["chǐ","耻"], ["xià","下"], ["wèn","问"], ["。","。"]],
      note: "《论语》《朱子语类》。敏而好学不耻下问；读书有三到：心到、眼到、口到。",
      recognize: [{ch:"矣",py:"yǐ",word:"矣"},{ch:"耻",py:"chǐ",word:"耻辱"},{ch:"谓",py:"wèi",word:"所谓"}],
      write: [{ch:"耻",py:"chǐ",strokes:10,radical:"耳",word:"耻辱"},{ch:"诲",py:"huì",strokes:9,radical:"讠",word:"教诲"},{ch:"诵",py:"sòng",strokes:9,radical:"讠",word:"诵读"},{ch:"岂",py:"qǐ",strokes:6,radical:"山",word:"岂能"}],
      practice: ["朗读并背诵。","读书三到是什么？","敏而好学讲什么？"],
      think: "你读书做到三到了吗？",
    }),
    gardenPage("八", ["识字加油站：读书字--诵、诲、耻、岂。","字词句运用：用「读书好，多读书，读好书」写感受。","书写提示：注意「诲」「诵」的讠旁。","日积月累：读书有三到，谓心到、眼到、口到。"], { zhTitle: "枫桥夜泊", lines: ["月落乌啼霜满天，", "江枫渔火对愁眠。", "姑苏城外寒山寺，", "夜半钟声到客船。"] }),

    strokePage("识字表（会认）", "五年级上册会认字约 180 个。重点：鹭、嫌、喙、黛、亩、吩、咐、榨、桂、箩、杭、汛、访、鞋、挽、璧、臣、蔺、颇、猎、酬、珍、叮、郎、爹、嫂、恳、哉、渊、鳞、殿、珑、剔、烬、摄、氏、殖、粮、驯、栗、缨、魄、抑、颓、窠、旷、怡、桨、榕、耀、矣、耻、谓。"),
    strokePage("写字表（会写）", "五年级上册会写字约 180 个。重点：宜、鹤、嫌、韵、亩、播、吩、榨、懂、兰、箩、婆、汛、访、鞋、挽、召、臣、议、献、猎、酬、珍、叮、郎、爹、嫂、辆、泻、潜、试、胎、毁、估、拱、辉、摄、氏、殖、粮、鼠、秀、玲、珑、辞、抑、碌、噪、黎、晕、漆、幕、桨、榕、耀、暇、耻、诲、诵、岂。"),
    strokePage("词语表", "适宜、白鹤、嫌弃、韵味、半亩、播种、吩咐、榨油、懂得、兰花、箩筐、外婆、汛期、访问、鞋子、挽手、召集、大臣、议论、献出、打猎、酬谢、珍贵、叮嘱、牛郎、爹爹、嫂子、一辆、泻下、潜龙、试验、胎生、毁灭、估计、拱桥、辉煌、摄氏、姓氏、繁殖、粮食、松鼠、秀丽、玲珑、辞退、抑制、忙碌、噪音、黎明、红晕、漆黑、夜幕、船桨、榕树、照耀、应接不暇、耻辱、教诲、诵读、岂能。"),
    { kind: "back", title: { en: "Afterword", zh: "后记" }, body: { en: <>You finished Grade 5 Book One.</>, zh: <>你读完了五年级上册。五年级 · 下册 从这里继续。</> } },
  ],
};
