import type { Book } from "@/components/BookReader";
import { lessonPage, gardenPage, speakPage, unitPage, poemPage, strokePage } from "./grade1";

// 六年级 · 上册（部编版六年级上册结构）
export const grade6Book: Book = {
  gradeId: "g6",
  title: { en: "Grade 6 · Book One", zh: "六年级 · 上册" },
  subtitle: { en: "Land, Heroes & Masters", zh: "土地、英雄与大师" },
  pages: [
    { kind: "cover", title: { en: "Cover", zh: "封面" } },
    { kind: "copyright", title: { en: "About", zh: "出版说明" }, body: { en: <>Grade 6 Book One, after the PEP sixth-grade textbook.</>, zh: <>《六年级 · 上册》，按部编版六年级上册结构编写。</> } },
    { kind: "toc", title: { en: "Contents", zh: "目录" } },

    unitPage("一", "触摸自然", "Touching Nature", "草原、丁香结、花之歌。", ["草原", "丁香结", "花之歌"]),
    ...lessonPage({
      zhTitle: "草原", enTitle: "The Grassland", pinyin: "cǎo yuán",
      passage: [["zhè","这"],["cì","次"],["，","，"],["w","我"],["k","看"],["d","到"],["l","了"],["c","草"],["y","原"],["。","。"]],
      note: "老舍。草原风光美，蒙古族人民热情好客，蒙汉情深。景美、人美、情美。",
      recognize: [{ch:"毯",py:"tǎn",word:"绿毯"},{ch:"陈",py:"chén",word:"陈列"},{ch:"裳",py:"shang",word:"衣裳"},{ch:"虹",py:"hóng",word:"彩虹"}],
      write: [{ch:"毯",py:"tǎn",strokes:12,radical:"毛",word:"绿毯"},{ch:"陈",py:"chén",strokes:7,radical:"阝",word:"陈列"},{ch:"蹄",py:"tí",strokes:16,radical:"足",word:"马蹄"},{ch:"腐",py:"fǔ",strokes:14,radical:"肉",word:"豆腐"}],
      practice: ["朗读课文。","草原风光怎样？","蒙古族人民怎么待客？"],
      think: "「蒙汉情深何忍别」是什么意思？",
    }),
    ...lessonPage({
      zhTitle: "丁香结", enTitle: "The Lilac Knot", pinyin: "dīng xiāng jié",
      passage: [["jīn","今"],["nián","年"],["d","丁"],["xiāng","香"],["huā","花"],["k","开"],["de","得"],["g","格"],["w","外"],["m","茂"],["shèng","盛"], ["。","。"]],
      note: "宗璞。丁香花苞像衣襟上的盘花扣（结）。结是解不完的，人生问题也解不完，要豁达。",
      recognize: [{ch:"缀",py:"zhuì",word:"点缀"},{ch:"幽",py:"yōu",word:"幽雅"},{ch:"雅",py:"yǎ",word:"幽雅"},{ch:"案",py:"àn",word:"案头"}],
      write: [{ch:"缀",py:"zhuì",strokes:11,radical:"纟",word:"点缀"},{ch:"幽",py:"yōu",strokes:9,radical:"幺",word:"幽静"},{ch:"雅",py:"yǎ",strokes:12,radical:"隹",word:"优雅"},{ch:"拙",py:"zhuō",strokes:8,radical:"扌",word:"笨拙"}],
      practice: ["朗读课文。","丁香结指什么？","作者从丁香结悟到什么？"],
      think: "你怎么看人生的「结」？",
    }),
    ...lessonPage({
      zhTitle: "花之歌", enTitle: "Song of the Flower", pinyin: "huā zhī gē",
      passage: [["w","我"],["shì","是"],["d","大"],["zì","自"],["rán","然"],["de","的"],["huà","话"],["yǔ","语"],["。","。"]],
      note: "纪伯伦。以花的口吻自述：我是大自然的话语、星星、诸元素之女。散文诗，想象丰富。",
      recognize: [{ch:"冕",py:"miǎn",word:"冠冕"},{ch:"祭",py:"jì",word:"祭献"},{ch:"曳",py:"yè",word:"摇曳"}],
      write: [{ch:"氛",py:"fēn",strokes:8,radical:"气",word:"气氛"},{ch:"曳",py:"yè",strokes:6,radical:"曰",word:"摇曳"},{ch:"冠",py:"guān",strokes:9,radical:"冖",word:"花冠"},{ch:"冕",py:"miǎn",strokes:11,radical:"冂",word:"冠冕"}],
      practice: ["朗读课文。","花把自己比作什么？","表达了什么情感？"],
      think: "用一种事物自述，你会选什么？",
    }),
    speakPage("演讲：观点要明确", "做一次演讲，观点明确、有说服力。", ["观点要明确。", "用事例支撑。"], ["我演讲：读书使人充实。", "我演讲：保护环境从我做起。"]),
    gardenPage("一", ["识字加油站：自然字--毯、幽、雅、冕。","字词句运用：用比喻写草原。","书写提示：注意「毯」「冕」的结构。","日积月累：过故人庄--故人具鸡黍，邀我至田家。"], { zhTitle: "过故人庄", lines: ["故人具鸡黍，", "邀我至田家。", "绿树村边合，", "青山郭外斜。"] }),

    unitPage("二", "革命岁月", "Revolutionary Years", "七律长征、狼牙山五壮士、开国大典。", ["七律·长征", "狼牙山五壮士", "开国大典"]),
    ...lessonPage({
      zhTitle: "七律·长征", enTitle: "The Long March", pinyin: "qī lǜ cháng zhēng",
      passage: [["h","红"],["j","军"],["b","不"],["p","怕"],["yuǎn","远"],["zhēng","征"],["n","难"], ["，","，"],["w","万"],["shuǐ","水"],["qiān","千"],["shān","山"],["zhǐ","只"],["děng","等"],["xián","闲"],["。","。"]],
      note: "毛泽东。红军不怕远征难。五岭、乌蒙、金沙、大渡、岷山，革命乐观主义。",
      recognize: [{ch:"律",py:"lǜ",word:"七律"},{ch:"崖",py:"yá",word:"云崖"},{ch:"渡",py:"dù",word:"渡桥"},{ch:"岷",py:"mín",word:"岷山"}],
      write: [{ch:"律",py:"lǜ",strokes:9,radical:"彳",word:"纪律"},{ch:"崖",py:"yá",strokes:11,radical:"山",word:"山崖"},{ch:"渡",py:"dù",strokes:12,radical:"氵",word:"渡河"},{ch:"索",py:"suǒ",strokes:10,radical:"糸",word:"铁索"}],
      practice: ["朗读并背诵。","红军克服了哪些困难？","表现了什么精神？"],
      think: "「只等闲」体现什么态度？",
    }),
    ...lessonPage({
      zhTitle: "狼牙山五壮士", enTitle: "The Five Heroes of Langya Mountain", pinyin: "láng yá shān wǔ zhuàng shì",
      passage: [["w","五"],["z","壮"],["shì","士"],["w","为"],["l","了"],["b","保"],["h","护"],["q","群"],["zhòng","众"],["h","和"],["b","部"],["d","队"], ["，","，"],["b","把"],["d","敌"],["r","人"],["y","引"],["shàng","上"],["l","狼"],["y","牙"],["shān","山"], ["。","。"]],
      note: "五壮士为掩护群众和部队，把敌人引上绝路，最后跳崖。英勇不屈、视死如归。",
      recognize: [{ch:"寇",py:"kòu",word:"日寇"},{ch:"副",py:"fù",word:"副班长"},{ch:"抡",py:"lūn",word:"抡拳"},{ch:"绷",py:"běng",word:"绷脸"}],
      write: [{ch:"寇",py:"kòu",strokes:11,radical:"宀",word:"敌寇"},{ch:"副",py:"fù",strokes:11,radical:"刂",word:"副手"},{ch:"抡",py:"lūn",strokes:7,radical:"扌",word:"抡起"},{ch:"悬",py:"xuán",strokes:11,radical:"心",word:"悬崖"}],
      practice: ["朗读课文。","五壮士做了哪些事？","表现了什么精神？"],
      think: "为什么称他们壮士？",
    }),
    ...lessonPage({
      zhTitle: "开国大典", enTitle: "The Founding Ceremony", pinyin: "kāi guó dà diǎn",
      passage: [["y","一"],["jiǔ","九"],["sì","四"],["jiǔ","九"],["nián","年"],["shí","十"],["yuè","月"],["yī","一"],["r","日"], ["，","，"],["zhōng","中"],["huá","华"],["rén","人"],["mín","民"],["gòng","共"],["hé","和"],["guó","国"],["zhōng","中"],["yāng","央"],["rén","人"],["mín","民"],["zhèng","政"],["fǔ","府"],["chéng","成"],["lì","立"], ["。","。"]],
      note: "1949年10月1日开国大典，毛主席宣布中华人民共和国成立，阅兵、群众游行。庄严、自豪。",
      recognize: [{ch:"典",py:"diǎn",word:"大典"},{ch:"政",py:"zhèng",word:"政府"},{ch:"宾",py:"bīn",word:"外宾"},{ch:"栏",py:"lán",word:"栏杆"}],
      write: [{ch:"典",py:"diǎn",strokes:8,radical:"八",word:"大典"},{ch:"政",py:"zhèng",strokes:9,radical:"攵",word:"政府"},{ch:"府",py:"fǔ",strokes:8,radical:"广",word:"政府"},{ch:"制",py:"zhì",strokes:8,radical:"刂",word:"制度"}],
      practice: ["朗读课文。","大典有哪些程序？","场面怎样？"],
      think: "人们为什么激动？",
    }),
    gardenPage("二", ["识字加油站：革命字--寇、典、政、府。","字词句运用：用点面结合写场面。","书写提示：注意「典」「府」的结构。","日积月累：鞠躬尽瘁，死而后已。"], { zhTitle: "春日", lines: ["胜日寻芳泗水滨，", "无边光景一时新。", "等闲识得东风面，", "万紫千红总是春。"] }),

    unitPage("三", "阅读策略", "Reading Strategy", "竹节人、宇宙生命之谜、故宫博物院。", ["竹节人", "宇宙生命之谜", "故宫博物院"]),
    ...lessonPage({
      zhTitle: "竹节人", enTitle: "The Bamboo Joint Man", pinyin: "zhú jié rén",
      passage: [["w","我"],["men","们"],["xiǎng","想"],["w","玩"],["zhú","竹"],["jié","节"],["r","人"], ["。","。"]],
      note: "做竹节人、斗竹节人是童年乐趣。根据不同目的采用不同阅读方法。",
      recognize: [{ch:"疙",py:"gē",word:"疙瘩"},{ch:"瘩",py:"da",word:"疙瘩"},{ch:"棍",py:"gùn",word:"木棍"},{ch:"裁",py:"cái",word:"裁剪"}],
      write: [{ch:"疙",py:"gē",strokes:8,radical:"疒",word:"疙瘩"},{ch:"瘩",py:"da",strokes:14,radical:"疒",word:"疙瘩"},{ch:"棍",py:"gùn",strokes:12,radical:"木",word:"木棍"},{ch:"裁",py:"cái",strokes:12,radical:"衣",word:"裁剪"}],
      practice: ["根据目的选择读法。","怎么做竹节人？","斗竹节人有趣在哪？"],
      think: "你玩过什么自制玩具？",
    }),
    gardenPage("三", ["识字加油站：阅读方法--精读、略读、跳读。","字词句运用：根据目的选读法。","书写提示：注意「疙」「瘩」的疒旁。","日积月累：春日。"], { zhTitle: "回乡偶书", lines: ["少小离家老大回，", "乡音无改鬓毛衰。", "儿童相见不相识，", "笑问客从何处来。"] }),

    unitPage("四", "小说人物", "Fiction Characters", "桥、穷人、在柏林。", ["桥", "穷人", "在柏林"]),
    ...lessonPage({
      zhTitle: "桥", enTitle: "The Bridge", pinyin: "qiáo",
      passage: [["l","老"],["zhī","支"],["shū","书"],["jì","记"],["zhàn","站"],["z","在"],["m","木"],["qiáo","桥"],["qián","前"], ["。","。"]],
      note: "山洪暴发，老支书指挥村民过桥，最后和儿子牺牲。无私、舍己为人。结尾出人意料。",
      recognize: [{ch:"咆",py:"páo",word:"咆哮"},{ch:"哮",py:"xiào",word:"咆哮"},{ch:"嗓",py:"sǎng",word:"嗓子"},{ch:"搀",py:"chān",word:"搀扶"}],
      write: [{ch:"咆",py:"páo",strokes:8,radical:"口",word:"咆哮"},{ch:"哮",py:"xiào",strokes:10,radical:"口",word:"咆哮"},{ch:"嗓",py:"sǎng",strokes:13,radical:"口",word:"嗓子"},{ch:"淌",py:"tǎng",strokes:11,radical:"氵",word:"流淌"}],
      practice: ["朗读课文。","老支书做了什么？","结尾有什么特点？"],
      think: "老支书是个怎样的人？",
    }),
    ...lessonPage({
      zhTitle: "穷人", enTitle: "The Poor", pinyin: "qióng rén",
      passage: [["y","渔"],["f","夫"],["de","的"],["qī","妻"],["zi","子"],["sāng","桑"],["nà","娜"],["b","抱"],["huí","回"],["l","了"],["lín","邻"],["jū","居"],["de","的"],["liǎng","两"],["gè","个"],["hái","孩"],["zi","子"], ["。","。"]],
      note: "列夫·托尔斯泰。桑娜和渔夫自己穷，仍抱回邻居孤儿。善良、宁可自己受苦也要帮人。",
      recognize: [{ch:"寡",py:"guǎ",word:"寡妇"},{ch:"蜷",py:"quán",word:"蜷缩"},{ch:"魁",py:"kuí",word:"魁梧"},{ch:"黧",py:"lí",word:"黧黑"}],
      write: [{ch:"汹",py:"xiōng",strokes:7,radical:"氵",word:"汹涌"},{ch:"涌",py:"yǒng",strokes:10,radical:"氵",word:"汹涌"},{ch:"澎",py:"péng",strokes:15,radical:"氵",word:"澎湃"},{ch:"湃",py:"pài",strokes:12,radical:"氵",word:"澎湃"}],
      practice: ["朗读课文。","桑娜和渔夫做了什么决定？","表现了什么品质？"],
      think: "穷人「穷」在哪里，「富」在哪里？",
    }),
    gardenPage("四", ["识字加油站：人物字--寡、蜷、魁、黧。","字词句运用：用心理描写写人物。","书写提示：注意「汹」「湃」的氵旁。","日积月累：少小离家老大回。"], { zhTitle: "宿建德江", lines: ["移舟泊烟渚，", "日暮客愁新。", "野旷天低树，", "江清月近人。"] }),

    unitPage("五", "围绕中心", "Around the Center", "夏天里的成长、盼。", ["夏天里的成长", "盼"]),
    ...lessonPage({
      zhTitle: "夏天里的成长", enTitle: "Growing in Summer", pinyin: "xià tiān lǐ de chéng zhǎng",
      passage: [["xià","夏"],["tiān","天"],["shì","是"],["wàn","万"],["wù","物"],["xùn","迅"],["sù","速"],["shēng","生"],["zhǎng","长"],["de","的"],["jì","季"],["jié","节"], ["。","。"]],
      note: "夏天是万物迅速生长的季节。人要赶时候、赶热天，尽量地用力地长。",
      recognize: [{ch:"棚",py:"péng",word:"瓜棚"},{ch:"苔",py:"tái",word:"苔藓"},{ch:"藓",py:"xiǎn",word:"苔藓"},{ch:"蔗",py:"zhè",word:"甘蔗"}],
      write: [{ch:"棚",py:"péng",strokes:12,radical:"木",word:"瓜棚"},{ch:"苔",py:"tái",strokes:8,radical:"艹",word:"苔藓"},{ch:"藓",py:"xiǎn",strokes:19,radical:"艹",word:"苔藓"},{ch:"谚",py:"yàn",strokes:11,radical:"讠",word:"谚语"}],
      practice: ["朗读课文。","夏天哪些事物在长？","人为什么要赶时候长？"],
      think: "你怎么「尽量地长」？",
    }),
    ...lessonPage({
      zhTitle: "盼", enTitle: "Longing", pinyin: "pàn",
      passage: [["y","有"],["y","一"],["tiān","天"],["，","，"],["mā","妈"],["ma","妈"],["gěi","给"],["w","我"],["m","买"],["l","了"],["y","一"],["jiàn","件"],["xīn","新"],["yǔ","雨"],["yī","衣"], ["。","。"]],
      note: "我得到新雨衣，盼下雨穿。细腻写出「盼」的心情。",
      recognize: [{ch:"蕾",py:"lěi",word:"花蕾"},{ch:"窸",py:"xī",word:"窸窣"},{ch:"窣",py:"sū",word:"窸窣"}],
      write: [{ch:"袖",py:"xiù",strokes:10,radical:"衤",word:"袖子"},{ch:"篷",py:"péng",strokes:16,radical:"竹",word:"斗篷"},{ch:"缩",py:"suō",strokes:14,radical:"纟",word:"缩小"},{ch:"甩",py:"shuǎi",strokes:5,radical:"甩",word:"甩手"}],
      practice: ["朗读课文。","我为什么盼下雨？","哪些细节写出「盼」？"],
      think: "你「盼」过什么？",
    }),
    gardenPage("五", ["识字加油站：成长字--棚、苔、藓、谚。","字词句运用：围绕中心写一段话。","书写提示：注意「篷」「缩」的结构。","日积月累：六月二十七日望湖楼醉书--黑云翻墨未遮山，白雨跳珠乱入船。"], { zhTitle: "六月二十七日望湖楼醉书", lines: ["黑云翻墨未遮山，", "白雨跳珠乱入船。", "卷地风来忽吹散，", "望湖楼下水如天。"] }),

    unitPage("六", "珍惜家园", "Our Home", "只有一个地球、青山不老、三黑和土地。", ["只有一个地球", "青山不老", "三黑和土地"]),
    ...lessonPage({
      zhTitle: "只有一个地球", enTitle: "Only One Earth", pinyin: "zhǐ yǒu yí gè dì qiú",
      passage: [["j","据"],["f","飞"],["x","行"],["z","宙"],["y","宇"],["h","航"],["y","员"],["j","介"],["shào","绍"] , ["，","，"],["dì","地"],["qiú","球"],["shì","是"],["y","一"],["gè","个"],["jīng","晶"],["yíng","莹"],["de","的"],["lán","蓝"],["sè","色"],["x","星"],["qiú","球"], ["。","。"]],
      note: "地球美丽渺小、资源有限、不能移居。我们要精心保护地球。",
      recognize: [{ch:"莹",py:"yíng",word:"晶莹"},{ch:"裹",py:"guǒ",word:"裹着"},{ch:"蔼",py:"ǎi",word:"和蔼"},{ch:"慨",py:"kǎi",word:"慷慨"}],
      write: [{ch:"莹",py:"yíng",strokes:10,radical:"艹",word:"晶莹"},{ch:"裹",py:"guǒ",strokes:14,radical:"衣",word:"包裹"},{ch:"蔼",py:"ǎi",strokes:14,radical:"艹",word:"和蔼"},{ch:"慨",py:"kǎi",strokes:12,radical:"忄",word:"慷慨"}],
      practice: ["默读课文。","地球有什么特点？","为什么要保护地球？"],
      think: "你能为地球做什么？",
    }),
    gardenPage("六", ["识字加油站：环保字--莹、裹、蔼、慨。","字词句运用：用「因为……所以……」说保护地球。","书写提示：注意「裹」「慨」的结构。","日积月累：五行--金木水火土；五谷--稻麦黍菽稷。"], { zhTitle: "浪淘沙", lines: ["九曲黄河万里沙，", "浪淘风簸自天涯。", "如今直上银河去，", "同到牵牛织女家。"] }),

    unitPage("七", "艺术之美", "The Beauty of Art", "伯牙鼓琴、月光曲、京剧趣谈。", ["伯牙鼓琴", "月光曲", "京剧趣谈"]),
    ...lessonPage({
      zhTitle: "伯牙鼓琴", enTitle: "Boya Plays the Qin", pinyin: "bó yá gǔ qín",
      passage: [["b","伯"],["y","牙"],["g","鼓"],["q","琴"], ["，","，"],["zhōng","钟"],["z","子"],["q","期"],["t","听"],["zhī","之"], ["。","。"]],
      note: "文言文。伯牙善鼓琴，钟子期善听（知音）。子期死，伯牙破琴绝弦。知音难觅。",
      recognize: [{ch:"哉",py:"zāi",word:"善哉"},{ch:"巍",py:"wēi",word:"巍巍"},{ch:"弦",py:"xián",word:"琴弦"}],
      write: [{ch:"哉",py:"zāi",strokes:9,radical:"口",word:"善哉"},{ch:"巍",py:"wēi",strokes:20,radical:"山",word:"巍峨"},{ch:"弦",py:"xián",strokes:8,radical:"弓",word:"琴弦"},{ch:"轴",py:"zhóu",strokes:9,radical:"车",word:"画轴"}],
      practice: ["朗读并背诵文言文。","为什么伯牙破琴绝弦？","知音是什么？"],
      think: "你有知音吗？",
    }),
    ...lessonPage({
      zhTitle: "月光曲", enTitle: "Moonlight Sonata", pinyin: "yuè guāng qǔ",
      passage: [["y","一"],["bǎi","百"],["duō","多"],["nián","年"],["qián","前"],["，","，"],["y","有"],["gè","个"],["rén","人"],["shuō","说"],["，","，"],["bèi","贝"],["duō","多"],["fēn","芬"],["t","听"],["w","为"],["m","盲"],["gū","姑"],["niang","娘"],["tán","弹"],["q","琴"], ["。","。"]],
      note: "贝多芬为盲姑娘弹琴，即兴创作《月光曲》。音乐的美与同情心。",
      recognize: [{ch:"谱",py:"pǔ",word:"乐谱"},{ch:"莱",py:"lái",word:"莱茵河"},{ch:"茵",py:"yīn",word:"莱茵河"},{ch:"盲",py:"máng",word:"盲人"}],
      write: [{ch:"谱",py:"pǔ",strokes:14,radical:"讠",word:"乐谱"},{ch:"莱",py:"lái",strokes:10,radical:"艹",word:"莱茵"},{ch:"茵",py:"yīn",strokes:9,radical:"艹",word:"绿茵"},{ch:"盲",py:"máng",strokes:8,radical:"目",word:"盲人"}],
      practice: ["朗读课文。","贝多芬为什么弹琴？","月光曲描绘了什么？"],
      think: "音乐能表达什么？",
    }),
    gardenPage("七", ["识字加油站：艺术字--谱、莱、茵、盲。","字词句运用：用联想写音乐。","书写提示：注意「谱」「茵」的结构。","日积月累：高山流水、天籁之音、余音绕梁--音乐成语。"], { zhTitle: "书湖阴先生壁", lines: ["茅檐长扫净无苔，", "花木成畦手自栽。", "一水护田将绿绕，", "两山排闼送青来。"] }),

    unitPage("八", "走近鲁迅", "Approaching Lu Xun", "少年闰土、好的故事、我的伯父鲁迅先生。", ["少年闰土", "好的故事", "我的伯父鲁迅先生"]),
    ...lessonPage({
      zhTitle: "少年闰土", enTitle: "Young Runtu", pinyin: "shào nián rùn tǔ",
      passage: [["shēn","深"],["l","蓝"],["de","的"],["tiān","天"],["kōng","空"],["zhōng","中"],["guà","挂"],["zhe","着"],["y","一"],["lún","轮"],["jīn","金"],["huáng","黄"],["de","的"],["yuán","圆"],["yuè","月"], ["。","。"]],
      note: "鲁迅。闰土会捕鸟、捡贝壳、看瓜刺猹，见多识广。「我」只看见院子里高墙上的四角的天空。",
      recognize: [{ch:"闰",py:"rùn",word:"闰土"},{ch:"猬",py:"wèi",word:"刺猬"},{ch:"伶",py:"líng",word:"伶俐"},{ch:"俐",py:"lì",word:"伶俐"}],
      write: [{ch:"闰",py:"rùn",strokes:7,radical:"门",word:"闰月"},{ch:"猬",py:"wèi",strokes:12,radical:"犭",word:"刺猬"},{ch:"伶",py:"líng",strokes:7,radical:"亻",word:"伶俐"},{ch:"俐",py:"lì",strokes:9,radical:"亻",word:"伶俐"}],
      practice: ["朗读课文。","闰土讲了哪几件事？","「我」和闰土有什么不同？"],
      think: "四角的天空指什么？",
    }),
    ...lessonPage({
      zhTitle: "我的伯父鲁迅先生", enTitle: "My Uncle Lu Xun", pinyin: "wǒ de bó fù lù xùn",
      passage: [["b","伯"],["f","父"],["l","鲁"],["x","迅"],["x","先"],["sheng","生"],["shì","是"],["w","我"],["j","敬"],["ài","爱"],["de","的"],["r","人"], ["。","。"]],
      note: "周晔。鲁迅为自己想得少、为别人想得多。谈《水浒》、笑谈碰壁、救助车夫、关心女佣。",
      recognize: [{ch:"殡",py:"bìn",word:"殡仪"},{ch:"悼",py:"dào",word:"追悼"},{ch:"唁",py:"yàn",word:"吊唁"}],
      write: [{ch:"殡",py:"bìn",strokes:10,radical:"歹",word:"殡仪"},{ch:"悼",py:"dào",strokes:11,radical:"忄",word:"追悼"},{ch:"唁",py:"yàn",strokes:10,radical:"口",word:"吊唁"},{ch:"浒",py:"hǔ",strokes:9,radical:"氵",word:"水浒"}],
      practice: ["朗读课文。","课文写了鲁迅哪几件事？","鲁迅是个怎样的人？"],
      think: "「为自己想得少、为别人想得多」怎么理解？",
    }),
    gardenPage("八", ["识字加油站：鲁迅字--闰、猬、伶、俐。","字词句运用：用事例写一个人。","书写提示：注意「悼」「唁」的结构。","日积月累：无情未必真豪杰，怜子如何不丈夫。"], { zhTitle: "江南春", lines: ["千里莺啼绿映红，", "水村山郭酒旗风。", "南朝四百八十寺，", "多少楼台烟雨中。"] }),

    strokePage("识字表（会认）", "六年级上册会认字约 180 个。重点：毯、陈、裳、虹、缀、幽、雅、案、冕、祭、曳、律、崖、渡、岷、寇、副、抡、绷、典、政、宾、栏、疙、瘩、棍、裁、咆、哮、嗓、搀、寡、蜷、魁、黧、棚、苔、藓、蔗、蕾、窸、窣、莹、裹、蔼、慨、哉、巍、弦、谱、莱、茵、盲、闰、猬、伶、俐、殡、悼、唁。"),
    strokePage("写字表（会写）", "六年级上册会写字约 180 个。重点：毯、陈、蹄、腐、缀、幽、雅、拙、氛、曳、冠、冕、律、崖、渡、索、寇、副、抡、悬、典、政、府、制、疙、瘩、棍、裁、咆、哮、嗓、淌、汹、涌、澎、湃、棚、苔、藓、谚、袖、篷、缩、甩、莹、裹、蔼、慨、哉、巍、弦、轴、谱、莱、茵、盲、闰、猬、伶、俐、殡、悼、唁、浒。"),
    strokePage("词语表", "绿毯、陈列、马蹄、豆腐、点缀、幽静、优雅、笨拙、气氛、摇曳、花冠、冠冕、纪律、山崖、渡河、铁索、敌寇、副手、抡起、悬崖、大典、政府、制度、疙瘩、木棍、裁剪、咆哮、嗓子、流淌、汹涌、澎湃、瓜棚、苔藓、谚语、袖子、斗篷、缩小、甩手、晶莹、包裹、和蔼、慷慨、善哉、巍峨、琴弦、画轴、乐谱、莱茵、绿茵、盲人、闰月、刺猬、伶俐、殡仪、追悼、吊唁、水浒。"),
    { kind: "back", title: { en: "Afterword", zh: "后记" }, body: { en: <>You finished Grade 6 Book One - the last elementary book.</>, zh: <>你读完了六年级上册--小学最后一册。初中从这里继续。</> } },
  ],
};
