import type { Book } from "@/components/BookReader";
import { lessonPage, shiziPage, gardenPage, speakPage, unitPage, poemPage, strokePage } from "./grade1";

// 三年级 · 上册（部编版三年级上册结构）
export const grade3Book: Book = {
  gradeId: "g3",
  title: { en: "Grade 3 · Book One", zh: "三年级 · 上册" },
  subtitle: { en: "School, Seasons & Stories", zh: "学校、季节与故事" },
  pages: [
    { kind: "cover", title: { en: "Cover", zh: "封面" } },
    { kind: "copyright", title: { en: "About", zh: "出版说明" }, body: { en: <>Grade 3 Book One, after the PEP third-grade textbook.</>, zh: <>《三年级 · 上册》，按部编版三年级上册结构编写。</> } },
    { kind: "toc", title: { en: "Contents", zh: "目录" } },

    unitPage("一", "学校生活", "School Life", "我们的学校和花的学校。", ["大青树下的小学", "花的学校", "不懂就要问"]),
    ...lessonPage({
      zhTitle: "大青树下的小学", enTitle: "The School under the Big Banyan", pinyin: "dà qīng shù xià de xiǎo xué",
      passage: [["zǎo","早"],["chen","晨"],["，","，"],["cóng","从"],["shān","山"],["pō","坡"],["shàng","上"],["，","，"],["cóng","从"],["píng","坪"],["bà","坝"],["lǐ","里"],["，","，"],["cóng","从"],["yí","一"],["tiáo","条"],["tiáo","条"],["kai","开"],["mǎn","满"],["róng","绒"],["qiú","球"],["huā","花"],["de","的"],["xiǎo","小"],["lù","路"],["shàng","上"],["，","，"],["zǒu","走"],["lái","来"],["le","了"],["xǔ","许"],["duō","多"],["xiǎo","小"],["xué","学"],["shēng","生"],["。","。"]],
      note: "边疆的小学，不同民族的孩子一起上学、上课、做游戏。大青树、铜钟、凤尾竹，校园很美。",
      recognize: [{ch:"坝",py:"bà",word:"坪坝"},{ch:"绒",py:"róng",word:"绒球"},{ch:"戴",py:"dài",word:"穿戴"},{ch:"招",py:"zhāo",word:"招呼"},{ch:"蝴",py:"hú",word:"蝴蝶"},{ch:"蝶",py:"dié",word:"蝴蝶"}],
      write: [{ch:"晨",py:"chén",strokes:11,radical:"日",word:"早晨"},{ch:"绒",py:"róng",strokes:9,radical:"纟",word:"绒球"},{ch:"球",py:"qiú",strokes:11,radical:"王",word:"小球"},{ch:"汉",py:"hàn",strokes:5,radical:"氵",word:"汉族"}],
      practice: ["朗读课文，读出校园的美。","这所小学有什么特别的地方？","同学们上课时窗外怎样？"],
      think: "你的学校和这所小学有什么不同？",
    }),
    ...lessonPage({
      zhTitle: "花的学校", enTitle: "The Flower School", pinyin: "huā de xué xué",
      passage: [["dāng","当"],["léi","雷"],["yún","云"],["zài","在"],["tiān","天"],["shàng","上"],["hōng","轰"],["xiǎng","响"],["，","，"],["liù","六"],["yuè","月"],["de","的"],["yù","雨"],["shuǐ","水"],["luò","落"],["xià","下"],["de","的"],["shí","时"],["hou","候"],["，","，"],["yì","一"],["qún","群"],["yì","一"],["qún","群"],["de","的"],["huā","花"],["cóng","从"],["wú","无"],["rén","人"],["zhī","知"],["dào","道"],["de","的"],["dì","地"],["fāng","方"],["tū","突"],["rán","然"],["pǎo","跑"],["chū","出"],["lái","来"],["。","。"]],
      note: "泰戈尔的诗。花孩子们在地下的学校上学，雨一来就放假跑出来。想象丰富。",
      recognize: [{ch:"荒",py:"huāng",word:"荒野"},{ch:"笛",py:"dí",word:"口笛"},{ch:"罚",py:"fá",word:"罚站"},{ch:"假",py:"jià",word:"放假"}],
      write: [{ch:"落",py:"luò",strokes:12,radical:"艹",word:"落下"},{ch:"荒",py:"huāng",strokes:9,radical:"艹",word:"荒野"},{ch:"笛",py:"dí",strokes:11,radical:"竹",word:"口笛"},{ch:"狂",py:"kuáng",strokes:7,radical:"犭",word:"狂欢"}],
      practice: ["朗读课文。","花孩子的学校在哪里？","雨一来，花孩子们怎样？"],
      think: "你觉得花孩子的妈妈是谁？",
    }),
    ...lessonPage({
      zhTitle: "不懂就要问", enTitle: "Ask When You Don't Understand", pinyin: "bù dǒng jiù yào wèn",
      passage: [["sūn","孙"],["zhōng","中"],["shān","山"],["xiǎo","小"],["shí","时"],["hou","候"],["zài","在"],["sī","私"],["shú","塾"],["dú","读"],["shū","书"],["。","。"]],
      note: "孙中山在私塾读书，敢于提问：不懂就要问。勤学好问的精神。",
      recognize: [{ch:"孙",py:"sūn",word:"孙中山"},{ch:"塾",py:"shú",word:"私塾"},{ch:"诵",py:"sòng",word:"背诵"},{ch:"例",py:"lì",word:"照例"}],
      write: [{ch:"孙",py:"sūn",strokes:6,radical:"子",word:"孙子"},{ch:"诵",py:"sòng",strokes:9,radical:"讠",word:"背诵"},{ch:"例",py:"lì",strokes:8,radical:"亻",word:"例子"},{ch:"段",py:"duàn",strokes:9,radical:"殳",word:"一段"}],
      practice: ["朗读课文。","孙中山为什么提问？","先生怎么回答？"],
      think: "你遇到不懂的会怎么做？",
    }),
    gardenPage("一", ["识字加油站：校园里的字--操场、教室、图书角。","字词句运用：用「有……有……还有……」写校园。","书写提示：左右结构的字注意宽窄。","日积月累：所见--牧童骑黄牛，歌声振林樾。"], { zhTitle: "所见", lines: ["牧童骑黄牛，", "歌声振林樾。", "意欲捕鸣蝉，", "忽然闭口立。"] }),

    unitPage("二", "秋天", "Autumn", "秋天的雨和金色的小道。", ["秋天的雨", "铺满金色巴掌的水泥道", "古诗三首"]),
    ...lessonPage({
      zhTitle: "秋天的雨", enTitle: "Autumn Rain", pinyin: "qiū tiān de yǔ",
      passage: [["qiū","秋"],["tiān","天"],["de","的"],["yǔ","雨"],["，","，"],["shì","是"],["yì","一"],["bǎ","把"],["yào","钥"],["shi","匙"],["。","。"]],
      note: "秋天的雨是钥匙，有一盒五彩缤纷的颜料，藏着好闻的气味，吹起金色的小喇叭。",
      recognize: [{ch:"钥",py:"yào",word:"钥匙"},{ch:"匙",py:"shi",word:"钥匙"},{ch:"缤",py:"bīn",word:"缤纷"},{ch:"纷",py:"fēn",word:"缤纷"}],
      write: [{ch:"盒",py:"hé",strokes:11,radical:"皿",word:"一盒"},{ch:"颜",py:"yán",strokes:15,radical:"页",word:"颜色"},{ch:"料",py:"liào",strokes:10,radical:"斗",word:"颜料"},{ch:"票",py:"piào",strokes:11,radical:"示",word:"邮票"}],
      practice: ["朗读课文，背诵喜欢的段落。","秋天的雨把颜色给了谁？","秋天的雨里藏着什么气味？"],
      think: "秋天的雨还会把颜色给谁？",
    }),
    ...lessonPage({
      zhTitle: "铺满金色巴掌的水泥道", enTitle: "The Path of Golden Palms", pinyin: "pū mǎn jīn sè bā zhǎng de shuǐ ní dào",
      passage: [["yí","一"],["yè","夜"],["qiū","秋"],["fēng","风"],["，","，"],["yí","一"],["yè","夜"],["qiū","秋"],["yǔ","雨"],["。","。"]],
      note: "法国梧桐的落叶像金色的小巴掌，铺满水泥道，很美。善于发现身边的美。",
      recognize: [{ch:"洼",py:"wā",word:"水洼"},{ch:"印",py:"yìn",word:"印着"},{ch:"凌",py:"líng",word:"凌乱"},{ch:"棕",py:"zōng",word:"棕红"}],
      write: [{ch:"铺",py:"pū",strokes:12,radical:"钅",word:"铺满"},{ch:"泥",py:"ní",strokes:8,radical:"氵",word:"水泥"},{ch:"院",py:"yuàn",strokes:9,radical:"阝",word:"院子"},{ch:"墙",py:"qiáng",strokes:14,radical:"土",word:"墙角"}],
      practice: ["朗读课文。","金色巴掌指什么？","为什么水泥道很美？"],
      think: "你发现过身边的美吗？",
    }),
    poemPage("山行", "杜牧", [["yuǎn","远"],["shàng","上"],["hán","寒"],["shān","山"],["shí","石"],["jìng","径"],["xié","斜"],["，","，"],["bái","白"],["yún","云"],["shēng","生"],["chù","处"],["yǒu","有"],["rén","人"],["jiā","家"],["。","。"],["tíng","停"],["chē","车"],["zuò","坐"],["ài","爱"],["fēng","枫"],["lín","林"],["wǎn","晚"],["，","，"],["shuāng","霜"],["yè","叶"],["hóng","红"],["yú","于"],["èr","二"],["yuè","月"],["huā","花"],["。","。"]], "沿石径上寒山，白云处有人家。停车爱枫林，霜叶红于二月花。", "写秋天枫叶比春花还红。"),
    gardenPage("二", ["识字加油站：秋天的字--霜、叶、落、丰。","字词句运用：用比喻写落叶。","书写提示：上下结构的字注意重心。","日积月累：秋词--自古逢秋悲寂寥，我言秋日胜春朝。"], { zhTitle: "赠刘景文", lines: ["荷尽已无擎雨盖，", "菊残犹有傲霜枝。", "一年好景君须记，", "最是橙黄橘绿时。"] }),

    unitPage("三", "童话", "Fairy Tales", "去年的树、在牛肚子里旅行、总也倒不了的老屋。", ["去年的树", "在牛肚子里旅行", "总也倒不了的老屋"]),
    ...lessonPage({
      zhTitle: "去年的树", enTitle: "Last Year's Tree", pinyin: "qù nián de shù",
      passage: [["yì","一"],["kē","棵"],["shù","树"],["hé","和"],["yì","一"],["zhī","只"],["niǎo","鸟"],["r","儿"],["shì","是"],["hǎo","好"],["péng","朋"],["you","友"],["。","。"]],
      note: "鸟儿答应给树唱歌。树被砍了，鸟儿对着灯火唱去年的歌。信守承诺、珍惜友情。",
      recognize: [{ch:"伐",py:"fá",word:"砍伐"},{ch:"融",py:"róng",word:"融化"},{ch:"煤",py:"méi",word:"煤油"}],
      write: [{ch:"冷",py:"lěng",strokes:7,radical:"冫",word:"寒冷"},{ch:"离",py:"lí",strokes:10,radical:"亠",word:"离开"},{ch:"等",py:"děng",strokes:12,radical:"竹",word:"等待"},{ch:"剩",py:"shèng",strokes:12,radical:"刂",word:"剩下"}],
      practice: ["分角色朗读。","鸟儿答应树什么？","鸟儿最后对着什么唱歌？"],
      think: "鸟儿为什么对着灯火唱？",
    }),
    ...lessonPage({
      zhTitle: "在牛肚子里旅行", enTitle: "A Trip in the Cow's Stomach", pinyin: "zài niú dǔ zi lǐ lǚ xíng",
      passage: [["yǒu","有"],["liǎng","两"],["zhī","只"],["xiǎo","小"],["xī","蟋"],["shuài","蟀"],["，","，"],["yì","一"],["zhī","只"],["jiào","叫"],["hóng","红"],["tou","头"],["，","，"],["yì","一"],["zhī","只"],["jiào","叫"],["qīng","青"],["tou","头"],["。","。"]],
      note: "红头被牛吃进肚子，青头用知识救它。牛有四个胃、会反刍。科学+友情。",
      recognize: [{ch:"蟋",py:"xī",word:"蟋蟀"},{ch:"蟀",py:"shuài",word:"蟋蟀"},{ch:"嚼",py:"jiáo",word:"细嚼"},{ch:"反",py:"fǎn",word:"反刍"}],
      write: [{ch:"旅",py:"lǚ",strokes:10,radical:"方",word:"旅行"},{ch:"咱",py:"zán",strokes:9,radical:"口",word:"咱们"},{ch:"偷",py:"tōu",strokes:11,radical:"亻",word:"偷偷"},{ch:"救",py:"jiù",strokes:11,radical:"攵",word:"救命"}],
      practice: ["朗读课文。","红头在牛肚子里经过了哪些地方？","青头怎么救红头？"],
      think: "牛为什么会反刍？",
    }),
    ...lessonPage({
      zhTitle: "总也倒不了的老屋", enTitle: "The Old House That Never Falls", pinyin: "zǒng yě dǎo bù liǎo de lǎo wū",
      passage: [["lǎo","老"],["wū","屋"],["yǐ","已"],["jīng","经"],["hěn","很"],["lǎo","老"],["lǎo","老"],["le","了"],["。","。"]],
      note: "老屋为了帮小猫、老母鸡、小蜘蛛，一直不倒。乐于助人、善良。",
      recognize: [{ch:"暴",py:"bào",word:"暴风雨"},{ch:"凑",py:"còu",word:"凑近"},{ch:"喵",py:"miāo",word:"喵喵"}],
      write: [{ch:"洞",py:"dòng",strokes:9,radical:"氵",word:"门洞"},{ch:"准",py:"zhǔn",strokes:10,radical:"冫",word:"准备"},{ch:"备",py:"bèi",strokes:8,radical:"夂",word:"准备"},{ch:"暴",py:"bào",strokes:15,radical:"日",word:"暴雨"}],
      practice: ["朗读课文。","老屋帮了谁？","老屋为什么总也不倒？"],
      think: "你想对老屋说什么？",
    }),
    speakPage("名字里的故事", "向别人介绍自己名字的故事或含义。", ["说清楚名字的含义。", "听别人讲，可以提问。"], ["我的名字叫「晨」，因为我在早晨出生。","我名字里的「睿」是智慧的意思。"]),
    gardenPage("三", ["识字加油站：反义词--安静-热闹、旧-新。","字词句运用：用「一边……一边……」写童话。","书写提示：注意「旅」「救」的笔顺。","日积月累：灯不拨不亮，理不辩不明。"], { zhTitle: "夜书所见", lines: ["萧萧梧叶送寒声，", "江上秋风动客情。", "知有儿童挑促织，", "夜深篱落一灯明。"] }),

    unitPage("四", "观察与发现", "Observation", "搭船的鸟、金色的草地。", ["搭船的鸟", "金色的草地"]),
    ...lessonPage({
      zhTitle: "搭船的鸟", enTitle: "The Bird on the Boat", pinyin: "dā chuán de niǎo",
      passage: [["wǒ","我"],["hé","和"],["mǔ","母"],["qīn","亲"],["zuò","坐"],["zhe","着"],["xiǎo","小"],["chuán","船"],["。","。"]],
      note: "一只翠鸟搭我们的船捕鱼。仔细观察，发现翠鸟的美和捕鱼的本领。",
      recognize: [{ch:"搭",py:"dā",word:"搭船"},{ch:"翠",py:"cuì",word:"翠绿"},{ch:"嘴",py:"zuǐ",word:"嘴巴"},{ch:"悄",py:"qiāo",word:"悄悄"}],
      write: [{ch:"搭",py:"dā",strokes:12,radical:"扌",word:"搭船"},{ch:"翠",py:"cuì",strokes:14,radical:"羽",word:"翠绿"},{ch:"嘴",py:"zuǐ",strokes:16,radical:"口",word:"嘴巴"},{ch:"吞",py:"tūn",strokes:7,radical:"口",word:"吞下"}],
      practice: ["朗读课文。","翠鸟长什么样？","它怎么捕鱼？"],
      think: "你观察过什么小动物？",
    }),
    ...lessonPage({
      zhTitle: "金色的草地", enTitle: "The Golden Meadow", pinyin: "jīn sè de cǎo dì",
      passage: [["wǒ","我"],["men","们"],["zhù","住"],["zài","在"],["xiāng","乡"],["xià","下"],["，","，"],["chuāng","窗"],["qián","前"],["shì","是"],["yí","一"],["piàn","片"],["cǎo","草"],["dì","地"],["。","。"]],
      note: "草地早上绿色、中午金色、傍晚又绿，因为蒲公英花瓣会张开合上。观察发现变化。",
      recognize: [{ch:"蒲",py:"pú",word:"蒲公英"},{ch:"英",py:"yīng",word:"蒲公英"},{ch:"瓣",py:"bàn",word:"花瓣"},{ch:"拢",py:"lǒng",word:"合拢"}],
      write: [{ch:"蒲",py:"pú",strokes:13,radical:"艹",word:"蒲公英"},{ch:"英",py:"yīng",strokes:8,radical:"艹",word:"英雄"},{ch:"瓣",py:"bàn",strokes:19,radical:"辛",word:"花瓣"},{ch:"拢",py:"lǒng",strokes:8,radical:"扌",word:"合拢"}],
      practice: ["朗读课文。","草地颜色为什么变化？","你从中学到什么？"],
      think: "你观察过植物的变化吗？",
    }),
    gardenPage("四", ["识字加油站：观察动词--看、听、闻、摸。","字词句运用：用「先……接着……然后……」写观察。","书写提示：注意「翠」「嘴」的结构。","日积月累：采莲曲--荷叶罗裙一色裁，芙蓉向脸两边开。"], { zhTitle: "望天门山", lines: ["天门中断楚江开，", "碧水东流至此回。", "两岸青山相对出，", "孤帆一片日边来。"] }),

    unitPage("五", "祖国山河", "Our Land", "富饶的西沙群岛、海滨小城、美丽的小兴安岭。", ["富饶的西沙群岛", "海滨小城", "美丽的小兴安岭"]),
    ...lessonPage({
      zhTitle: "富饶的西沙群岛", enTitle: "The Rich Xisha Islands", pinyin: "fù ráo de xī shā qún dǎo",
      passage: [["xī","西"],["shā","沙"],["qún","群"],["dǎo","岛"],["fēng","风"],["jǐng","景"],["yōu","优"],["měi","美"],["，","，"],["wù","物"],["chǎn","产"],["fēng","丰"],["fù","富"],["。","。"]],
      note: "西沙群岛海水五光十色，海底有珊瑚、海参、大龙虾、鱼，海岛上有鸟。风景优美、物产丰富。",
      recognize: [{ch:"饶",py:"ráo",word:"富饶"},{ch:"屿",py:"yǔ",word:"岛屿"},{ch:"珊",py:"shān",word:"珊瑚"},{ch:"瑚",py:"hú",word:"珊瑚"}],
      write: [{ch:"富",py:"fù",strokes:12,radical:"宀",word:"富饶"},{ch:"饶",py:"ráo",strokes:9,radical:"饣",word:"富饶"},{ch:"优",py:"yōu",strokes:6,radical:"亻",word:"优美"},{ch:"浅",py:"qiǎn",strokes:8,radical:"氵",word:"浅水"}],
      practice: ["朗读课文。","西沙群岛的海水为什么五光十色？","海底有哪些生物？"],
      think: "你想去西沙群岛吗？",
    }),
    ...lessonPage({
      zhTitle: "美丽的小兴安岭", enTitle: "Beautiful Xiaoxing'an Mountains", pinyin: "měi lì de xiǎo xīng ān lǐng",
      passage: [["wǒ","我"],["guó","国"],["dōng","东"],["běi","北"],["de","的"],["xiǎo","小"],["xīng","兴"],["ān","安"],["lǐng","岭"],["，","，"],["yǒu","有"],["shù","数"],["bù","不"],["qīng","清"],["de","的"],["hóng","红"],["sōng","松"],["。","。"]],
      note: "小兴安岭春夏秋冬景色各异，是美丽的大花园、巨大的宝库。",
      recognize: [{ch:"兴",py:"xīng",word:"兴安岭"},{ch:"岭",py:"lǐng",word:"山岭"},{ch:"膝",py:"xī",word:"膝盖"},{ch:"浸",py:"jìn",word:"浸在"}],
      write: [{ch:"岭",py:"lǐng",strokes:8,radical:"山",word:"山岭"},{ch:"季",py:"jì",strokes:8,radical:"子",word:"四季"},{ch:"抽",py:"chōu",strokes:8,radical:"扌",word:"抽出"},{ch:"嫩",py:"nèn",strokes:14,radical:"女",word:"嫩绿"}],
      practice: ["朗读课文。","小兴安岭四季各有什么景色？","为什么说它是宝库？"],
      think: "你最喜欢哪个季节的小兴安岭？",
    }),
    gardenPage("五", ["识字加油站：地名--西沙群岛、小兴安岭、海滨。","字词句运用：用「有的……有的……」写海底。","书写提示：注意「富」「饶」的结构。","日积月累：早发白帝城--朝辞白帝彩云间，千里江陵一日还。"], { zhTitle: "饮湖上初晴后雨", lines: ["水光潋晴方好，", "山色空蒙雨亦奇。", "欲把西湖比西子，", "淡妆浓抹总相宜。"] }),

    unitPage("六", "大自然的声音", "Nature's Sounds", "大自然的声音、读不完的大书。", ["大自然的声音", "读不完的大书"]),
    ...lessonPage({
      zhTitle: "大自然的声音", enTitle: "Sounds of Nature", pinyin: "dà zì rán de shēng yīn",
      passage: [["dà","大"],["zì","自"],["rán","然"],["yǒu","有"],["xǔ","许"],["duō","多"],["měi","美"],["miào","妙"],["de","的"],["shēng","声"],["yīn","音"],["。","。"]],
      note: "风是大自然的音乐家，水也是，动物是歌手。大自然的声音美妙。",
      recognize: [{ch:"妙",py:"miào",word:"美妙"},{ch:"奏",py:"zòu",word:"演奏"},{ch:"呢",py:"ní",word:"呢喃"},{ch:"喃",py:"nán",word:"呢喃"}],
      write: [{ch:"妙",py:"miào",strokes:7,radical:"女",word:"美妙"},{ch:"奏",py:"zòu",strokes:9,radical:"大",word:"演奏"},{ch:"琴",py:"qín",strokes:12,radical:"王",word:"钢琴"},{ch:"柔",py:"róu",strokes:9,radical:"木",word:"温柔"}],
      practice: ["朗读课文。","大自然有哪些声音？","风、水、动物各是什么？"],
      think: "你还听到过大自然的什么声音？",
    }),
    gardenPage("六", ["识字加油站：声音字--哗、轰、叽、喳。","字词句运用：用拟声词写一句话。","书写提示：注意「奏」「琴」的结构。","日积月累：采莲曲。"], { zhTitle: "望洞庭", lines: ["湖光秋月两相和，", "潭面无风镜未磨。", "遥望洞庭山水翠，", "白银盘里一青螺。"] }),

    unitPage("七", "美好品质", "Good Qualities", "司马光、掌声、灰雀。", ["司马光", "掌声", "灰雀"]),
    ...lessonPage({
      zhTitle: "司马光", enTitle: "Sima Guang", pinyin: "sī mǎ guāng",
      passage: [["qún","群"],["ér","儿"],["xì","戏"],["yú","于"],["tíng","庭"],["，","，"],["yì","一"],["ér","儿"],["dēng","登"],["wèng","瓮"],["，","，"],["zú","足"],["diē","跌"],["méi","没"],["shuǐ","水"],["。","。"]],
      note: "文言文。小孩掉进水缸，司马光砸缸救人。沉着机智。",
      recognize: [{ch:"司",py:"sī",word:"司马光"},{ch:"跌",py:"diē",word:"跌倒"},{ch:"皆",py:"jiē",word:"皆"},{ch:"弃",py:"qì",word:"放弃"}],
      write: [{ch:"司",py:"sī",strokes:5,radical:"口",word:"司机"},{ch:"庭",py:"tíng",strokes:9,radical:"广",word:"庭院"},{ch:"登",py:"dēng",strokes:12,radical:"癶",word:"登山"},{ch:"持",py:"chí",strokes:9,radical:"扌",word:"坚持"}],
      practice: ["朗读并背诵文言文。","小孩遇到什么危险？","司马光怎么做的？"],
      think: "司马光和其他孩子有什么不同？",
    }),
    ...lessonPage({
      zhTitle: "掌声", enTitle: "Applause", pinyin: "zhǎng shēng",
      passage: [["yīng","英"],["zi","子"],["yóu","犹"],["yù","豫"],["le","了"],["yí","一"],["huì","会"],["er","儿"],["，","，"],["màn","慢"],["màn","慢"],["dì","地"],["zhàn","站"],["le","了"],["qǐ","起"],["lái","来"],["。","。"]],
      note: "英子腿有残疾，上台时同学们给她掌声，鼓励了她。掌声给人信心和力量。",
      recognize: [{ch:"掌",py:"zhǎng",word:"掌声"},{ch:"斑",py:"bān",word:"斑纹"},{ch:"郁",py:"yù",word:"忧郁"}],
      write: [{ch:"掌",py:"zhǎng",strokes:12,radical:"手",word:"掌声"},{ch:"班",py:"bān",strokes:10,radical:"王",word:"班级"},{ch:"调",py:"diào",strokes:10,radical:"讠",word:"调动"},{ch:"投",py:"tóu",strokes:7,radical:"扌",word:"投入"}],
      practice: ["朗读课文。","同学们给了英子几次掌声？","掌声对英子有什么影响？"],
      think: "你给过别人掌声吗？",
    }),
    gardenPage("七", ["识字加油站：品质字--勇、诚、信、善。","字词句运用：用「因为……所以……」说司马光。","书写提示：注意「掌」「班」的结构。","日积月累：爱人若爱其身。"], { zhTitle: "早发白帝城", lines: ["朝辞白帝彩云间，", "千里江陵一日还。", "两岸猿声啼不住，", "轻舟已过万重山。"] }),

    unitPage("八", "想象与智慧", "Imagination", "父亲树林和鸟、手术台就是阵地。", ["父亲树林和鸟", "手术台就是阵地"]),
    ...lessonPage({
      zhTitle: "父亲、树林和鸟", enTitle: "Father, the Woods and Birds", pinyin: "fù qīn shù lín hé niǎo",
      passage: [["fù","父"],["qīn","亲"],["yì","一"],["shēng","生"],["zuì","最"],["xǐ","喜"],["huan","欢"],["shù","树"],["lín","林"],["hé","和"],["niǎo","鸟"],["。","。"]],
      note: "父亲能通过看树叶、闻气味知道鸟的存在，因为他爱鸟、懂鸟。",
      recognize: [{ch:"黎",py:"lí",word:"黎明"},{ch:"凝",py:"níng",word:"凝神"},{ch:"喃",py:"nán",word:"呢喃"}],
      write: [{ch:"朝",py:"cháo",strokes:12,radical:"月",word:"朝向"},{ch:"雾",py:"wù",strokes:13,radical:"雨",word:"雾气"},{ch:"蒙",py:"méng",strokes:13,radical:"艹",word:"蒙蒙"},{ch:"鼻",py:"bí",strokes:14,radical:"鼻",word:"鼻子"}],
      practice: ["朗读课文。","父亲怎么知道林中有鸟？","父亲爱鸟吗？从哪看出？"],
      think: "怎样才是真正爱鸟？",
    }),
    gardenPage("八", ["识字加油站：职业字--医、护、师、警。","字词句运用：用「无论……都……」写白求恩。","书写提示：注意「雾」「鼻」的结构。","日积月累：不迁怒，不贰过。"], { zhTitle: "采莲曲", lines: ["荷叶罗裙一色裁，", "芙蓉向脸两边开。", "乱入池中看不见，", "闻歌始觉有人来。"] }),

    strokePage("识字表（会认）", "三年级上册会认字约 250 个。重点：坝、绒、戴、招、蝴、蝶、荒、笛、罚、假、钥、匙、缤、纷、洼、印、凌、棕、伐、融、煤、蟋、蟀、嚼、反、暴、凑、喵、搭、翠、嘴、悄、蒲、英、瓣、拢、饶、屿、珊、瑚、兴、岭、膝、浸、妙、奏、呢、喃、司、跌、皆、弃、掌、斑、郁、黎、凝。"),
    strokePage("写字表（会写）", "三年级上册会写字约 250 个。重点：晨、绒、球、汉、落、荒、笛、狂、孙、诵、例、段、盒、颜、料、票、铺、泥、院、墙、冷、离、等、剩、旅、咱、偷、救、洞、准、备、暴、搭、翠、嘴、吞、蒲、英、瓣、拢、富、饶、优、浅、岭、季、抽、嫩、妙、奏、琴、柔、司、庭、登、持、掌、班、调、投、朝、雾、蒙、鼻。"),
    strokePage("词语表", "早晨、绒球、穿戴、招呼、蝴蝶、荒野、口笛、罚站、放假、钥匙、缤纷、水洼、凌乱、棕红、砍伐、融化、煤油、蟋蟀、旅行、救命、门洞、准备、暴风雨、搭船、翠绿、嘴巴、吞下、蒲公英、花瓣、合拢、富饶、优美、浅水、山岭、四季、抽出、嫩绿、美妙、演奏、钢琴、温柔、司机、庭院、登山、坚持、掌声、班级、调动、投入、朝向、雾气、蒙蒙、鼻子。"),
    { kind: "back", title: { en: "Afterword", zh: "后记" }, body: { en: <>You finished Grade 3 Book One.</>, zh: <>你读完了三年级上册。三年级 · 下册 从这里继续。</> } },
  ],
};
